### ISSUE TITLE
improve safety of KernelHeaderTmpDir()

### ISSUE THREAD

**Issue by brendangregg** [bpftrace/bpftrace#1026]
I just noticed this in utils.cpp:

```
    ~KernelHeaderTmpDir()               
    {                                            
      if (path.size() > 0) {                     
        // move_to either did not succeed or did not run, so clean up after ourselves
        exec_system(("rm -rf " + path).c_str());      
      }
    }
```

This ticket is a reminder to add more safety checks around this. Check the path string itself to make sure it looks like the right path.

**Comment by amscanne** [comment]
@jordalgo You removed this in bc73244963f206814ae45ec78ebe52cd389f6381 and I think it can be closed.
