### ISSUE TITLE
use std::filesystem

### ISSUE THREAD

**Issue by fbs** [bpftrace/bpftrace#1263]
Now that we have C++17 we can start making use of [std::filesystem](https://en.cppreference.com/w/cpp/filesystem) and start replacing  the `sprintf()` path concat and stat/access stuff with this.

**Comment by Horki** [comment]
@fbs @brendangregg please test #1704

**Comment by Horki** [comment]
@fbs this can be closed now right?

**Comment by fbs** [comment]
I still see some stat/access and path concat happening in various places

**Comment by jordalgo** [comment]
I think there may just be one left:
https://github.com/search?q=repo%3Aiovisor%2Fbpftrace+%3A%3Astat&type=code
