### ISSUE TITLE
More granular debugging options

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#131]
Rather than having the "-d" flag to print debug output, it would be nicer to have options to print only the debug output you're interested in.

Current types of debug output:
- AST
- LLVM IR
- BPF bytecode
- Tracepoint argument structs

Maybe this could be done as an argument to "-d", e.g. to only show AST debug output:
`bpftrace -d ast input.bt`

**Comment by amscanne** [comment]
@jordalgo This has been mostly implemented in b92cb694834351282bc225fd76b33093035c05dc.
