### ISSUE TITLE
Fully document language

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#1323]
Seems we have some language features not fully documented (like bitshift operators in #1322).

Would be good to go through language grammar and make sure everything is in the reference guide.

**Comment by mmisono** [comment]
The few things I noticed:

- the behavior of `str()` (#1010)
- using enum value
- pointer arithmetic (need to cast to integer fast)
- json output
- the detail of async functions (e.g., `@ = 1; zero(@); print("%d\n", @);`

**Comment by mmisono** [comment]
About floating-point values: #1343

**Comment by fbs** [comment]
working on a manpage where we can put all this stuff in, https://github.com/fbs/bpftrace/blob/manpage/man/adoc/bpftrace.adoc . The refguide can then be stripped down to a quick ref guide. Hope to have the basis ready for review soon so people can start helping extending.

**Comment by Nudin** [comment]
The syntax `print(@map, 10)` to limit to the top ten rows is also missing. [It seems to only work with global map variables?]

**Comment by danobi** [comment]
> The syntax `print(@map, 10)` to limit to the top ten rows is also missing. [It seems to only work with global map variables?]

@Nudin , are you thinking of this? https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#10-print-print-map

**Comment by Nudin** [comment]
> > The syntax `print(@map, 10)` to limit to the top ten rows is also missing. [It seems to only work with global map variables?]
> 
> @Nudin , are you thinking of this? https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#10-print-print-map

Oh, yes your right. I didn't realize that there are two separate chapters for the print function(s). The one links to the other but not vice versa. We might want to change that?

**Comment by fbs** [comment]
#1935 adds the print syntax to the manpage. Is there any more we need to add?

**Comment by danobi** [comment]
I think we're still missing docs on ptr dereference. Especially the stuff #1881 added

**Comment by danobi** [comment]
Need usdt documentation in man page too

**Comment by jordalgo** [comment]
Closing this for now as I think most is addressed in the updated adoc.
