### ISSUE TITLE
Support accessing percpu kernel data

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#1837]
There's a helper to access percpu data now: https://github.com/torvalds/linux/blob/0aa099a312b6323495a23d758009eb7fc04a7617/include/uapi/linux/bpf.h#L4489

However, it's not so simple to use. IIUC, there needs to be BTF ID to the data in question
in the right register when the helper is called. libbpf does these fixups and they look
somewhat complicated. So before we can support this we'll need to have libbpf do
our loading for us.

**Comment by danobi** [comment]
I think we should be unblocked on this. We should be able to emit a `__ksym` extern from codegen and then have libbpf relocate it for us. 

Following  also makes sense to me, as it stays consistent within bpftrace and is also familiar to kernel folks. eg

For API, I think we've got two obvious options:

```
per_cpu(kaddr("percpu_symbol"), 5);
this_cpu(kaddr("percpu_symbol");
```
or
```
per_cpu("percpu_symbol", 5);
this_cpu("percpu_symbol");
```

Option 1 follows existing `kptr` (https://bpftrace.org/docs/master.html#functions-kptr) pattern. But possibly unnecessarily verbose, as we'll have to require the literal kaddr(..) call in the first param. Since we need to generate an extern with the symbol name in codegen.

Option 2 departs a bit from kptr pattern but is more terse and probably more obvious.

I'd vote option 2.

cc @viktormalik

**Comment by jordalgo** [comment]
I like Option 2 and also the more explicit wording `per_cpu_kptr`. However, instead of two functions what about one function and then a builtin e.g. `this_cpu` or `current_cpu`?

Also is there no such thing as a user space pointer specific to a CPU (asking for a friend) ?

**Comment by danobi** [comment]
> I like Option 2 and also the more explicit wording `per_cpu_kptr`. However, instead of two functions what about one function and then a builtin e.g. `this_cpu` or `current_cpu`?

So something like this?
```
per_cpu("percpu_symbol", this_cpu);
per_cpu("percpu_symbol", 5);
```
ie an overload on the second param? 

> Also is there no such thing as a user space pointer specific to a CPU (asking for a friend) ?

There are userspace thread locals, but I'm not sure what the implementation is and if it differs between different standard libraries. Should probably look into that as well.

**Comment by viktormalik** [comment]
We already have the `cpu` builtin which does what `this_cpu` should do, right?

In terms of syntax, I also prefer the longer single-function variant, either `percpu_kptr` or `per_cpu_kptr`. I'd stick with one function but would consider making the second parameter optional:
```
percpu_kptr("percpu_symbol", 5);
percpu_kptr("percpu_symbol");        # implicitly chooses the current cpu
```

Also Clang has the `percpu` BTF tag which (IIUC) it should add to BTF entries for the percpu variables so we could even do the percpu access transparently. The problem is that we still need the other approach as most distros compile kernels with GCC which doesn't support BTF tags.

**Comment by danobi** [comment]
Optional second param makes sense. Consistent with other helpers we have. Long term it would be great to inject percpu access when we have the BTF information.

**Comment by viktormalik** [comment]
Ok, let me take this one.
