### ISSUE TITLE
[RFC] Reading debug info from userspace binaries

### ISSUE THREAD

**Issue by viktormalik** [bpftrace/bpftrace#1901]
### Is your feature request related to a problem? Please describe.

I'm wondering if it makes sense to implement parsing of debug information from binaries.
 
Being able to do so would improve the experience of tracing (not only) userspace programs. Examples of features that would be possible:
- accessing (and printing) `uprobe` arguments by name (issue #1742)
- no need to include userspace headers to access struct fields
- `uprobe:line-number` probes (issue #1743)

### Describe the solution you'd like

Implement support for debug information. While DWARF seems to be the default choice, its support may have some downsides (at the very least introducing a new dependency on a parser library). As an alternative, we could support at least parsing of BTF for userspace programs, which shouldn't introduce any additional dependencies.

Has this been discussed before? Any opinions on this?

**Comment by danobi** [comment]
I think we've had some brief discussion before. IIRC a DWARF -> BTF converter was considered but IMO that's pretty hacky and not likely to work well.

In my opinion, DWARF is the way to go here. We'll support more languages and get access to stuff like location of local variables in frames. Could even uprobe by file and line number and access local variables.

Downside to DWARF is that libdwarf is quite slow and we'll take on another dependency.

**Comment by fbs** [comment]
+1 would be a nice addition to have.

It is another dependency but if we do it right it should be possible to just have it as a cmake flag without riddling the code with ifdefs, this logic can stay contained.

**Comment by viktormalik** [comment]
Ok then, I'll look into this and try to integrate DWARF support.

What about using libdw (from elfutils) instead of libdwarf? It's supposed to be faster, has a nicer API, and we're already using libelf so we have a dependency on elfutils anyway.

**Comment by danobi** [comment]
> What about using libdw (from elfutils) instead of libdwarf? It's supposed to be faster, has a nicer API, and we're already using libelf so we have a dependency on elfutils anyway.

Sounds perfect, then.

**Comment by mmisono** [comment]
FYI perf-probe has dwarf support, and it uses dwarf for not only arguments access but also stack unwinding. IIRC it works both kprobes and uprobes. (though I think we can't refer to the implementation since its license is GPL.)

**Comment by danobi** [comment]
I wrote up an initial design for DWARF based stack walks: https://dxuuu.xyz/stack-symbolize.html

**Comment by mmisono** [comment]
I forgot to mention, but perf-probe also utilizes DWARF to access local variables.

Example:

The source file
```c
#include <stdio.h>
int main(){
    int a = 1;
    int b = 2;
    int c = 3;
    int d = a+b*c;
    printf("%d\n", d);
    return 0;
}
```

```
% gcc -O0 -g a.c
```

Show line numbers
```
% sudo perf probe -x ./a.out --line main
<main@/home/ubuntu/work/bpftrace/build/a.c:0>
      0  int main(){
      1      int a = 1;
      2      int b = 2;
      3      int c = 3;
      4      int d = a+b*c;
      5      printf("%d\n", d);
      6      return 0;
      7  }
```

Print available variables at main:5
```
% sudo perf probe -x ./a.out -V "main:5"
Available variables at main:5
        @<main+46>
                int     a
                int     b
                int     c
                int     d
```

Show local variable locations
```
% sudo perf probe --dry-run -v -x ./a.out "main+47 a b c d"
...
Writing event: p:probe_a/main /home/ubuntu/work/bpftrace/build/a.out:0x678 a=-16(%bp):s32 b=-12(%bp):s32 c=-8(%bp):s32 d=-4(%bp):s32
Added new event:
  probe_a:main         (on main+46 in /home/ubuntu/work/bpftrace/build/a.out with a b c d)

You can now use it in all perf tools, such as:

        perf record -e probe_a:main -aR sleep 1
```

At the main+47, local variables a, b, c, d can be stored at -16(%bp), -12(%bp), -8(%bp), -4(%bp) respectively.

We can use this information to access local variables from bpftrace.

```
#include <linux/ptrace.h>

uprobe:./a.out:main+46 {
  $regs = (struct pt_regs*)ctx;
  $a = $regs->bp - 16;
  $b = $regs->bp - 12;
  $c = $regs->bp - 8;
  $d = $regs->bp - 4;
  printf("a=%d b=%d c=%d d=%d\n", *$a, *$b, *$c, *$c);
}
```

```
% sudo ./src/bpftrace probe.bt
Attaching 1 probe...
a=1 b=2 c=3 d=3
^C
```

This also works for krpobes.

**Comment by barathrm** [comment]
I haven't seen it mentioned anywhere so I'll do it here; any thoughts on adding something like #1966 for USDT probes? Simply listing the number of arguments and possibly their type would be a big help already.

**Comment by viktormalik** [comment]
> I haven't seen it mentioned anywhere so I'll do it here; any thoughts on adding something like #1966 for USDT probes? Simply listing the number of arguments and possibly their type would be a big help already.

Getting the number of arguments should be possible. As for the types, if I understand correctly, they are all integers (and you're supposed to cast them to the correct type). Although BCC has function [bcc_usdt_get_probe_argctype](https://github.com/iovisor/bcc/blob/master/src/cc/bcc_usdt.h#L83-L85), it will esentially only return the size of the integer, so that's not of much help. DWARF contains no information on USDT probes.

**Comment by viktormalik** [comment]
bpftrace now has a good support for working with DWARF, closing this.
