### ISSUE TITLE
Filter on arbitrary level of map key

### ISSUE THREAD

**Issue by BurntBrunch** [bpftrace/bpftrace#2267]
### Is your feature request related to a problem? Please describe.
When you're collecting stacks that correspond to specific work items (e.g., workqueue items but other groupings naturally exist), you are tempted to do use `@[$itemid, kstack()]` for storage.

Unfortunately, the only way you can then print or delete this map is in its entirety. 

### Describe the solution you'd like
It would be great to have a primitive like `filter(@, 0, $itemid)` which returns `@` with the 0th level equal to `$itemid`. Then, one could `print` or `delete` that subset to better manage output and storage requirements.

### Describe alternative solutions or features you've considered
This issue is related to #1470 but not the same. Batch operations require that you know the keys of all the elements you are trying to manipulate. The result of `filter` could be that subset of keys, so that subsequent `delete()` operations use batch ops underneath. 

That said, there's no real mechanism to iterate and discover all relevant keys and that's what's this issue is about.

I'm open to implementing this, if we can figure out the design. Filter expressions are relevant here though they feel like opening a bigger can of worms than strict equality matching.

**Comment by fbs** [comment]
> It would be great to have a primitive like filter(@, 0, $itemid) which returns @ with the 0th level equal to $itemid. Then, one could print or delete that subset to better manage output and storage requirements.

What do you mean by `0th level` here?

One potential issue is that the `delete` is handled in bpf but afaik there is no way to iterate map keys. So this delete would have to be handled in userspace which can lead to surprising issues.

Not sure what a good solution would be here

**Comment by BurntBrunch** [comment]
> What do you mean by 0th level here?

Sorry, that was poorly worded. I'm suggesting that `filter(@, 0, $val)` can return the subset of keys where the first element of the tuple (`a` in `(a, b, c)`) equals `$val`. `filter(@, 1, $val)` would compare the second element in the tuple, etc. In a way, this allows tuple keys to become multi-level keys.

> One potential issue is that the delete is handled in bpf but afaik there is no way to iterate map keys. So this delete would have to be handled in userspace which can lead to surprising issues.

`bpf_for_each_map_elem` [exists now](https://lore.kernel.org/bpf/20210226204925.3884923-1-yhs@fb.com/), so this shouldn't be a problem on newer kernels (looks like it landed in 5.13).

**Comment by fbs** [comment]
Ah I missed that for_each gets the key as callback. If delete is allowed from the callback it would be interesting.

**Comment by BurntBrunch** [comment]
> If delete is allowed from the callback it would be interesting.

It is allowed for hash maps, [here it is in the tests](https://github.com/torvalds/linux/blob/941e3e7912696b9fbe3586083a7c2e102cee7a87/tools/testing/selftests/bpf/progs/for_each_hash_map_elem.c#L45).

What would be the best design to prototype here? I think for simplicity's sake a new `delete_by_key_level(map, key level, value)` would be easiest but I'm open to other suggestions. 

In _theory_, I like the idea of being able to hold sets of keys as values but I'm not sure it'd ever be useful outside of deleting them. Also in theory, I think it would be interesting to be able to provide your own callback to for_each_map_elem but that path feels even more complicated - we'd need first-level functions in the language at the minimum.

**Comment by fbs** [comment]
> What would be the best design to prototype here? I think for simplicity's sake a new `delete_by_key_level(map, key level, value)` would be easiest but I'm open to other suggestions.

Yeah that should be ok for a prototype

> 
> In _theory_, I like the idea of being able to hold sets of keys as values but I'm not sure it'd ever be useful outside of deleting them.

Its interesting but I think the limited stack size (512b) will get in the way of a simple approach. You might be able to offload it to a per cpu map but idk how that will perform.

And I also don't think it has a use outside of deleting keys 

>  Also in theory, I think it would be interesting to be able to provide your own callback to for_each_map_elem but that path feels even more complicated - we'd need first-level functions in the language at the minimum.

That would be a nice feature to have :)

**Comment by BurntBrunch** [comment]
Okay, I spent some time working on this and have a couple of concerns. Primarily, the way static functions (aka subprogs in bpf lingo) work is not compatible with how bpftrace emits or loads programs.

First, the libbpf convention is that callbacks are in .text while entry programs are in their own sections. This is not a big deal since we don't use the libbpf ELF parsing but it does mean that we have to manually prepend the callbacks to the programs we load. We could be smart and do what libbpf does (it only prepends used subprogs) or could just dump the entire .text.

Second, and more importantly, subprogs require .BTF.ext (aka func info) metadata to work. That's the only way the verifier can figure out the boundaries between functions but bpftrace does not currently pass this to the kernel. This is also why we don't get line data with verifier errors.

I see two paths going forward:

1. Patch bpftrace's current logic to emit .BTF.ext, relocate and strip it to the sections being loaded and give it to the kernel. This is hard and not very clean design-wise (given the assumed probe-to-section 1-1 mapping) but it's possible.
2. Make bpftrace emit in-memory libbpf-conformant ELF objects and use libbpf to open, relocate and load them. (The --emit-elf objects bpftrace currently produces are incomplete and cannot be loaded with libbpf afaict). I like this approach in that it hides all the program-loading details we don't care about and bpftrace can become more of a compiler and less of a loader. It does entrench libbpf more (to the point it might be a requirement) and I don't know how desirable that is.

Please chime in with opinions. I'll investigate how much work getting the pipeline to generate .BTF.ext is but long term that's a bit whack-a-mole-y.

**Comment by BurntBrunch** [comment]
> Patch bpftrace's current logic to emit .BTF.ext

Ha, and I thought this would be easy.. 
bpftrace is currently not using the DIBuilder at all. This means LLVM can't generate any debug symbols, let alone the BTF symbols the target requires. 

I'll try to do a first pass of DIBuilder integration only for function entries to get it to generate BTF.ext.

- [ ] DIBuilder usage tracking at least function definitions. Optionally, maybe tracking source locations.
- [ ] Emit ELF with .BTF.ext
- [ ] Pass func_info to kernel
- [ ] Get back to this issue and implement delete_filtered via map_for_each_elem

**Comment by jordalgo** [comment]
@viktormalik Do you recall what happened to code in @BurntBrunch 's PR - namely the stuff around wildcard based deletion?

**Comment by viktormalik** [comment]
@jordalgo yeah, it's in #2321. All commits except the one adding the deletion itself were merged into bpftrace. However, we discussed with @ajor that this may not be the path we want to follow and instead use nested maps for this usecase.

**Comment by jordalgo** [comment]
I think @ajor was going for ranged-based deletion because nested maps in bpf is very limited at the moment and I don't think it's worth trying to implement them in bpftrace yet. That being said, I wonder if we can do both range-based deletion and this wildcard option.

**Comment by viktormalik** [comment]
Sure, we can do both, my perception was that @ajor didn't want bpftrace to have two ways of achieving basically the same thing. But if the nested maps are still limited, we should probably go for range-based deletion as the feature seems to be a priority one.

I can reopen the PR with implementation from @BurntBrunch.

**Comment by ajor** [comment]
Yep, BPF's maps-in-maps is too limited for what we wanted to do, so range-deletes it is.

**Comment by viktormalik** [comment]
Reopened the PR (with small modifications): #2922

**Comment by ajor** [comment]
This is now possible with for-each loops: #3003
