### ISSUE TITLE
Support iterating and checking the key of associative arrays

### ISSUE THREAD

**Issue by caizixian** [bpftrace/bpftrace#2384]
### Is your feature request related to a problem? Please describe.
1. If I have an associative array with integer value, I could just use `if`, because querying a non-existing key returns 0. But if I have an associative array that has `count`s, I couldn't find a way to check whether a key is in the array, and using them as boolean operand in `if` is a type error.

2. I have some USDT probes that collect userspace addresses (in this particular case, static Rust strings, which are static char buffers and associated lengths). I want to collect the addresses, and handle them later to reduce the number of copying and printing. I want to be able to iterate the associative array. The pseudo code looks like this.
```
usdt {
    @str_len[arg0] = arg1;
    @str_count[arg0] = count();
}

END {
    for key, value in @str_count {
        printf("%s: %d\n", str(key, @str_len(key)), value);
    }
}
```

### Describe the solution you'd like
Have operators that allow iterating associative arrays and checking whether an array contains a given key.

### Describe alternative solutions or features you've considered
1. Implementing a `contains` operation should be possible in principle, for example, bcc supports [`lookup`](https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#19-maplookup) and I can check whether the return value is null.
2. I don't know whether such construct is possible, considering looping is not something will be fully supported, for good reasons! What I would do in `bcc` is to iterate the maps in userspace, but by then, you cannot read the memory of other processes right?, because it requires something equivalent to `bpf_probe_read_user()`.

**Comment by BurntBrunch** [comment]
> I don't know whether such construct is possible, considering looping is not something will be fully supported, for good reasons!

I wouldn't call the reasons _good_, just limitations :) 
Upstream bpf has `bpf_loop` and `bpf_map_for_each_elem` and I have some work in #2321 to use the latter to implement `delete_filter`, which can match on tuple sub-fields.

> Have operators that allow iterating associative arrays and checking whether an array contains a given key.

In my opinion, this wouldn't be a language construct (for .. in) but a function call with a custom callback. E.g. `iterate(@map, cb_fn)` where `cb_fn` is a local function, defined via new syntax. That feels far more powerful (as you can now delete, update, whatever) and if we need an actual loop, we can emit one in the backend (the opposite - convert a loop into a call + callback can sometimes be trickier).

**Comment by danobi** [comment]
Closing as dup of #2955 .
