### ISSUE TITLE
Improving the documentations

### ISSUE THREAD

**Issue by xh4n3** [bpftrace/bpftrace#2753]
Consensus reached from bpftrace meeting on Sep 5th, 2023
> * Let’s keep everything in one place: manual page
> * It’s generated from asciidoc which is rendered nicely on GitHub website
> * Reference guide should be either deleted or shortened (sort of a “quick start guide”, inspired by 6-page awk manual starting on page 106 of [UNIX programmer's manual](https://9p.io/7thEdMan/v7vol2b.pdf))

There will be several stages marching towards the desired final state, which includes:
1. Ensuring that the manual page covers everything that the reference guide currently has.
2. Creating a new quick start guide, either from scratch or by modifying the existing reference guide.
3. Developing a website to host the manual pages.

I'm creating this issue to track progresses. I will keep this updated.

Please leave comments if any ideas, thanks!

**Comment by jordalgo** [comment]
@xh4n3 Happy New Year and gentle ping :)

**Comment by xh4n3** [comment]
@jordalgo Thanks for the reminder :)

I'm sorry that due to a recent change in my job position, I am unable to continue contributing to this project 😞. I've truly learned a lot from this project and from collaborating with all of you, especially @viktormalik @danobi . Thank you so much ❤️ 

This particular improvement task might still be valuable, so I'll leave it open. Please feel free to take https://github.com/iovisor/bpftrace/pull/2754 branch and contiune.

**Comment by danobi** [comment]
Thanks for you contributions @xh4n3 ! You're welcome back any time :)

**Comment by jordalgo** [comment]
I'm sure there are still things we can do to improve documentation but we've done an initial pass and merged the adoc with the reference doc.
