### ISSUE TITLE
Counting concurrently

### ISSUE THREAD

**Issue by dw** [bpftrace/bpftrace#277]
Given a simple Python script that calls `ioctl()` with garbage (so that it sticks out):

````python
import fcntl

while 1:
    try:fcntl.ioctl(76542,765432)
    except Exception: pass
````

And a bpftrace script using every available means to count those events:

````
tracepoint:syscalls:sys_exit_ioctl
    /args->ret < 0/
{
    @runscalar = @runscalar + 1;
    @runcpu[cpu] = count();
    @runcount = count();
}

interval:s:1
{
    printf("\n\n\n");
    printf("cpu %d\n", cpu);
    print(@runscalar);
    print(@runcount);
    print(@runcpu);
    clear(@runscalar);
    clear(@runcount);
    clear(@runcpu);
}
````

On an 8 thread machine, we see that:

- With a single thread, all counts appear to more or less agree - roughly 500k calls/sec.
- With 2 threads, runscalar and runcount mostly agree that roughly 800k calls/sec are happening, however runcount regularly deviates by 2x or more, possibly due to clear() racing with another CPU in the process of updating the value
- With 2 threads, runcpu appears to suffer from the same problem -- occasionally twice as many events are reported (seemingly unrelated to interval delay)
- With 2 threads, the problem appears to snowball until it is reporting millions of extra events over many reporting intervals
- With 3 threads, runscalar indicates 900k calls/sec, and seems to be far off the expected 1.5m calls/sec
- With 3 threads after after 2 consecutive intervals that fired on time, runcpu can be seen with one bucket having double as many events as reported by the others

Example of all counts looking suspect:

````
ms: 1000, cpu 0
@runscalar: 1006754
@runcount: 1221697
@runcpu[6]: 425505
@runcpu[2]: 818408
@runcpu[0]: 1947663

ms: 999, cpu 0
@runscalar: 934129
@runcount: 1597779
@runcpu[6]: 393040
@runcpu[2]: 804994
@runcpu[0]: 1945031
````

I looked under the hood and saw per-cpu hash tables are used for all variables, although I didn't get as far as understanding how those tables are polled, summed and cleared. The expectation would be that print() could safely read and sum these per-cpu variables, but clear() and zero() might have a much harder time avoiding concurrent work modifications made by other CPUs.

I have no idea which, if any of these counts are accurate.  It looks like in any case, clear() is racing with the running probe, which has a temporary copy of the value loaded for incrementing?

At least in my mind, it seems impossible to provide a running counter like this with concurrent updates without the ability to somehow snapshot a table over reporting intervals, and calculate the difference from the previous snapshot, unless some other magic is going on under the hood. Otherwise there will always be a race, and overreporting due to multiple unsynchronized writers trying to increment or clear the buckets involved.

Is a variable copy feature something that might worth be looking at? Which of these mechanisms is safe and recommended? Thanks

**Comment by dw** [comment]
In the process of hunting for another variant, I found yet more strange behaviour:

````
BEGIN {
    $ii = 0;
    unroll(8) {
        @count[$ii] = 0;
        $ii = $ii + 1;
    }
}

tracepoint:syscalls:sys_enter_ioctl
    /args->fd == 76542/
{
    @count[cpu] = @count[cpu] + 1;
}

interval:s:1
{
    $acc = 0;
    $i = 0;
    unroll(8) {
        $acc = $acc + @count[$i];
        $i = $i + 1;
    };
    print(@count);
    printf("%ld\n", $acc);

    //printf("%d\n", $acc - @last_acc);
    @last_acc = $acc;
}
````

`$acc` has a garbage value unless the `print(@count)` is moved above the `unroll()`.

**Comment by amscanne** [comment]
Given that this is 6 years old, I'm sure all the context is gone and perhaps bugs that were there are now fixed or obsolete. However, I think this can be closed as my read is that this is a result of UX issues over anything else (@jordalgo).

My take is that there are two fundamental issues here:
- First, obviously the two probes are fundamentally racy and clobbering each other. This is why you have the `runscalar` and `runcount` variability and why it is difficult to reason about what is correct.
- Second, the much more fundamental issue is that maps are printed *by reference* and the scalar values are *copied by value*. So they may be printed at any moment, before or after the delete and will change (unlike the scalar values which are copied when the `print` actually fires). This is why I think you see the map values increasing as they are printed, as the probes are still running.

The [man page](https://github.com/bpftrace/bpftrace/blob/master/man/adoc/bpftrace.adoc#print) states:

> Note that maps are printed by reference while scalar values are copied. This means that updating and printing maps in a fast loop will likely result in bogus map values as the map will be updated before userspace gets the time to dump and print it.

But I can definitely see how this would be a foot gun and lead to surprising behavior.

**Comment by jordalgo** [comment]
Just to add to what @amscanne said. There is also [this issue](https://github.com/bpftrace/bpftrace/issues/3028) which discusses the topic of async vs sync map printing and this, now merged, feature to iterate over per-cpu maps to get the total  value: https://github.com/bpftrace/bpftrace/pull/3189

I think we can close this issue in favor of this one: 
- https://github.com/bpftrace/bpftrace/issues/3028
