### ISSUE TITLE
Redirect tool PRs to new bpftrace-tool-shed

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#2829]
As discussed in office hours, there will be a new repository to hold community contributed bpftrace tools. Until it's created, this ticket holds some state we need to remember.

**Comment by danobi** [comment]
For https://github.com/iovisor/bpftrace/pull/2593, @llaoj has asked to be notified when the new repo is created

**Comment by danobi** [comment]
https://github.com/iovisor/bpftrace/pull/2437 is a good candidate

**Comment by danobi** [comment]
https://github.com/iovisor/bpftrace/pull/1903 is a good candidate

**Comment by danobi** [comment]
https://github.com/iovisor/bpftrace/pull/1903 is good as well

**Comment by viktormalik** [comment]
another candidate: #2898

**Comment by jordalgo** [comment]
I guess we might be waiting on our new github home to do this? (cc @ajor)

**Comment by llaoj** [comment]
waiting for the new repo

**Comment by danobi** [comment]
New repo has been created: https://github.com/bpftrace/user-tools

Please send PRs!

I'll bump the existing PRs as well
