### ISSUE TITLE
Bump to C++20

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#2852]
The codebase does a lot of string processing. So far, we have a mix of:

* Inefficient string concat (eg. `std::string("hello") + " world" + " !"`) which is really inefficient cuz it constructs 2 temporaries
* `std::ostringstream` which is kinda difficult to visually parse
* `snprintf` and the usual C style drawbacks
* Probably more that I'm missing

C++20 contains `std::format` which neatly solves all the above problems. We should take a look at using that if we are ok bumping to C++20.

**Comment by danobi** [comment]
According to https://en.cppreference.com/w/cpp/compiler_support/20, std::format has support starting at gcc 13 and clang 17. So it's pretty bleeding edge still.

**Comment by danobi** [comment]
Alternatively, we could just depend on https://github.com/fmtlib/fmt and then codemod all the calls to `fmt::*` at some later point.

**Comment by jordalgo** [comment]
Switching to just use `fmt` seems like simpler/easier solution to fixing string processing issues.

**Comment by ajor** [comment]
`std::format` is probably too new to use, but C++ 20 brings a lot of other nice features that have been supported by GCC and Clang for years. C++ 23 is just about to be released, so I think it's time to upgrade to C++ 20 anyway.

**Comment by viktormalik** [comment]
Another nice feature is `std::set<T>::contains` which can be used instead of using `.find(...)` and comparing the result with `.end()`

**Comment by ajor** [comment]
Done in #3297
