### ISSUE TITLE
Invalid JSON with multiple top-level objects

### ISSUE THREAD

**Issue by viktormalik** [bpftrace/bpftrace#2902]
When printing multiple values (e.g. maps) in JSON format, we get a JSON doc with multiple top-level objects which is not a valid JSON according to the standards.

### What reproduces the bug? Provide code if possible.

Consider this bpftrace program printing 2 maps and the info about attached probes:
```
# bpftrace -f json -e 'BEGIN { @x = 1; @y = 2; exit(); }'
{"type": "attached_probes", "data": {"probes": 1}}
{"type": "map", "data": {"@x": 1}}
{"type": "map", "data": {"@y": 2}}
```

Trying to parse it with Python's JSON parser throws an exception:
```
# bpftrace -f json -e 'BEGIN { @x = 1; @y = 2; exit(); }' | python3 -c "import json, sys; json.loads(sys.stdin.read())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 4 column 1 (char 53)
```

To comply with the standard, the output should be:
```
[
  {"type": "attached_probes", "data": {"probes": 1}},
  {"type": "map", "data": {"@x": 1}},
  {"type": "map", "data": {"@y": 2}}
]
```

**Comment by danobi** [comment]
As discussed in office hours, it seems we've inadvertently implemented ndjson (https://github.com/ndjson/ndjson-spec). Since ndjson is a real thing, perhaps the test runner should just properly support it
