### ISSUE TITLE
Set up clang-tidy in CI

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#2971]
`clang-tidy` seems like a useful linter. C++ could really use all the linters it can get.

https://github.com/marketplace/actions/clang-tidy-review looks useful but it might
be nice to be able to run clang-tidy locally as well thru nix. Perhaps this action
is better for that: https://github.com/marketplace/actions/clang-tidy-action . ie.
run clang-tidy thru nix, get the output file, then use the action to post inline comments
on the PR.

Would also be nice to only clang-tidy on changed lines, much like git-clang-format.

**Comment by jordalgo** [comment]
+100 to more linting
