### ISSUE TITLE
kprobe:do_sys_open do not print anything 

### ISSUE THREAD

**Issue by bladechen** [bpftrace/bpftrace#2996]
as described here: 
https://github.com/bpftrace/bpftrace/blob/master/docs/reference_guide.md#2-kprobekretprobe-dynamic-tracing-kernel-level-arguments

### What reproduces the bug? Provide code if possible.

i type following command, but it does not print anything when i cat some files.

```
sudo bpftrace -e 'kprobe:do_sys_open { printf("opening: %s\n", str(arg1)); }'
Attaching 1 probe...
```

my linux kernel is
```

 uname -a
Linux ubuntu 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### `bpftrace --info` output

```
sudo bpftrace --info
System
  OS: Linux 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022
  Arch: x86_64

Build
  version: v0.14.0
  LLVM: 11.1.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: no
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): yes
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes

```

one more question is how can I know arg1 refers to the filename?
I guess it match the function in kernel code (version 5.15), the arg1 is filename, am i correct?
```
  long do_sys_open(int dfd, const char __user *filename, int flags, umode_t mode)
  {
    struct open_how how = build_open_how(flags, mode);
    return do_sys_openat2(dfd, filename, &how);
  }
```

**Comment by jordalgo** [comment]
Sorry, we need to update the docs for that example. If you're seeing no filenames printed it's because you need to call the `uptr` function to tell bpftrace that this is a userspace pointer e.g.
```
sudo bpftrace -e 'kprobe:do_sys_open { printf("opening: %s\n", str(uptr(arg1))); }'
```

If you're not seeing ANYTHING being printed (not even "opening: ") then it might be that `cat` is not calling this function. I wasn't seeing anything printed when calling `cat` on my machine (but I saw other background processes calling this function)

> I guess it match the function in kernel code (version 5.15), the arg1 is filename, am i correct?

Yeah exactly. Though you can have more structured args by using the kfunc/fentry for do_sys_open if it's available. You can check by running: `sudo bpftrace -l | grep "do_sys_open"`

**Comment by danobi** [comment]
I think `cat` is probably going thru `openat()` syscall which is why you're not seeing `open()` syscall kprobe

**Comment by bladechen** [comment]
> sudo bpftrace -l | grep "do_sys_open"

**Comment by bladechen** [comment]
> I think `cat` is probably going thru `openat()` syscall which is why you're not seeing `open()` syscall kprobe

yeah, it works.

**Comment by jordalgo** [comment]
> but for kbprob, is there anyway to find the args other than finding from kernel code

I don't believe so. For kprobes you have to go look at the kernel code.

**Comment by jordalgo** [comment]
Seems like this got resolved. Feel free to re-open if I missed something.
