### ISSUE TITLE
LLVM lifetimes ended too early

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3000]
```
BEGIN
{
  $blah = "abc";
  @x[$blah] = 1;
  @y[$blah] = 1; 
}
```

The variable `$blah` should be alive throughout the entire duration of the program, but inspecting the generated IR shows that its lifetime is ended after writing to `@x`, before it is used again when writing to `@y`. Its lifetime is then ended for a second time after its last use.

Generated IR with lines using `$blah` prefixed with `*`:
```
define i64 @BEGIN(ptr nocapture readnone %0) local_unnamed_addr section "s_BEGIN_1" !dbg !3 {
entry:
  %"@y_val" = alloca i64, align 8
  %"@x_val" = alloca i64, align 8
* %"$blah" = alloca [4 x i8], align 4
* call void @llvm.lifetime.start.p0(i64 -1, ptr nonnull %"$blah")
* store i32 6513249, ptr %"$blah", align 4
  call void @llvm.lifetime.start.p0(i64 -1, ptr nonnull %"@x_val")
  store i64 1, ptr %"@x_val", align 8
  %pseudo = tail call i64 @llvm.bpf.pseudo(i64 1, i64 0)
* %update_elem = call i64 inttoptr (i64 2 to ptr)(i64 %pseudo, ptr nonnull %"$blah", ptr nonnull %"@x_val", i64 0)
  call void @llvm.lifetime.end.p0(i64 -1, ptr nonnull %"@x_val")
* call void @llvm.lifetime.end.p0(i64 -1, ptr nonnull %"$blah")
  call void @llvm.lifetime.start.p0(i64 -1, ptr nonnull %"@y_val")
  store i64 1, ptr %"@y_val", align 8
  %pseudo1 = call i64 @llvm.bpf.pseudo(i64 1, i64 1)
* %update_elem2 = call i64 inttoptr (i64 2 to ptr)(i64 %pseudo1, ptr nonnull %"$blah", ptr nonnull %"@y_val", i64 0)
  call void @llvm.lifetime.end.p0(i64 -1, ptr nonnull %"@y_val")
* call void @llvm.lifetime.end.p0(i64 -1, ptr nonnull %"$blah")
  ret i64 0
}
```

I'm not sure what the real impact of this bug is, but I imagine that it has the potential to produce wrong results through variables being incorrectly assigned to share the same stack address.

**Comment by ajor** [comment]
This bug appears to caused by this code: https://github.com/bpftrace/bpftrace/blob/4c8b262aed6399a04126d2f5199d0d588924e6d2/src/ast/passes/codegen_llvm.cpp#L2816-L2819

Variables which "needMemcpy" are passed around as a reference to their stack location as an `AllocaInst`: https://github.com/bpftrace/bpftrace/blob/4c8b262aed6399a04126d2f5199d0d588924e6d2/src/ast/passes/codegen_llvm.cpp#L1426-L1428

The issue is limited to variables holding stack-based values which are used as map keys. A real-world bug caused by this has now cropped up: #3194.

**Comment by danobi** [comment]
I wonder if we're being too aggressive with lifetime annotations. One would think LLVM can analyze lifetimes without annotations. When I play with clang, I can't seem to get it to emit lifetime annotations: https://godbolt.org/z/z7abdMhEz . (I didn't try super hard)

**Comment by ajor** [comment]
Agreed that proper lifetime analysis seems to be the way forwards. LLVM (at least back in the pre 4.0 days) doesn't do lifetime analysis by default - that's why we introduced the manual lifetime markers in the first place. It definitely seems like something that it should be able to do, but I've never managed to find out the magic words.

Will put in a quick fix to leak memory for now - better to run out of stack space than return wrong results.

**Comment by ajor** [comment]
I managed to get Clang to emit lifetime markers: https://godbolt.org/z/59az7M9Ko

Code for reference:
```c
void foo(int *p) {
    int a = 0;
    *p += (int)&a;
    int b = 0;
    *p += (int)&b;
}
```

It doesn't look like LLVM optimises lifetimes - it considers both `a` and `b` to be alive at the same time and gives them different stack addresses. It might not be a problem for regular architectures, but with BPF's tiny stack it does make a difference.
