### ISSUE TITLE
Variables declared inside loop does not respect lexical scope

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#3017]
### What reproduces the bug? Provide code if possible.
```
#!/usr/bin/env bpftrace

BEGIN {
        $i = 0;
        while ($i < 1) {
                $j = 0;
                $i++;
        }

        print($j);
        exit();
}
```

```
$ $ sudo ./build/src/bpftrace ~/scratch/loop_var.bt
Attaching 1 probe...
0
```

I expect to see some error about `$j` being undefined.

### `bpftrace --info` output
```
$ sudo ./build/src/bpftrace --info
System
  OS: Linux 6.7.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 02 Feb 2024 17:03:55 +0000
  Arch: x86_64

Build
  version: v0.20.0-43-g6d9d8
  LLVM: 16.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes
  jiffies64: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: yes
  uprobe_multi: no
  raw_tp_special: yes
  iter: yes
```

**Comment by ajor** [comment]
If-statements as well 😢 

```
$ sudo bpftrace -e 'BEGIN { if (0) { $var = 1; } print($var) }'
Attaching 1 probe...
0
^C
```

**Comment by viktormalik** [comment]
> Fixing this would technically be backwards incompatible. But surely nobody is relying on this buggy behavior, right?

Right, we shouldn't maintain backwards compatibility of an obviously buggy behaviour.

**Comment by ajor** [comment]
See also #686

**Comment by danobi** [comment]
Man, I really licked this cookie. I'm gonna try to focus on all the half finished stuff I've got. So other folks should feel free to pick this up

**Comment by jordalgo** [comment]
I'll take it. Sounds like fun :)

**Comment by fbs** [comment]
Is having all variables probe scoped really that bad? Saying that

```
BEGIN {
        $i = 0;
        while ($i < 1) {
                $j = 0;
                $i++;
        }
```

is converted(hoisted) into:

```
BEGIN {
        var $i, $j; // not real syntax

        $i = 0;
        while ($i < 1) {
                $j = 0;
                $i++;
        }
```

Doesn't seem _that_ terrible to me. In a way its similar to python where if/for also do not start new scopes.

```
$ cat test.py
def something():
    for x in [1,2,3]:
        if x == 3:
            y = 5
        print(x)

    print(x)
    print(y)

something()

/tmp $ python3 test.py
1
2
3
3
5
```

**Comment by danobi** [comment]
I don't think python does hoisting. My understanding (which could be wrong) is that it just does dynamic lookups. Eg:

```
>>> for i in range(5):
...     if i == 3:
...             j = True
...
>>> print(j)
True

>>> for i in range(5):
...     if i == 6:
...             k = True
...
>>> print(k)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'k' is not defined
```

**Comment by danobi** [comment]
All variables being probe scoped is an interesting idea. I hadn't considered that nor thought to describe the current behavior that way.

**Comment by fbs** [comment]
> I don't think python does hoisting. My understanding (which could be wrong) is that it just does dynamic lookups. Eg:
> ...
> If python hoists, then you'd expect `k` to be 0, right?

Inded. Afaik `for` and `if`  don't start a new block/scope so its all the same scope. `i` and j`j are both bound. The 2nd example shows the 'line by line' nature of python, `k` is unknown because the line is never evaluated. 

Javascript (which does hoisting) is quite weird (who guessed?) in that `var` hoists, even outside `if, but `let` doesn't:

```
function bla() {
  var x = 1;
  console.log(x);

  if (true) {
    var y = 1;
    let yy = 1;
    console.log(y, yy);
  }

  console.log(y, yy);
}

bla()
```

```
1
1 1
/private/tmp/test.js:11
  console.log(y, yy);
                 ^

ReferenceError: yy is not defined
```

**Comment by danobi** [comment]
While I think looking at other languages is useful to see what's been done and how it played out, I think we should be careful to start from first principles here, as we are somewhat in language design. Contrasted to syntax where I think it's less important to innovate.

What are our goals with this change? Is it to make the language more terse for one-liners? To prevent programming errors? To back out of a dead-end design choice (accidental or otherwise)? Something else? And what are the relative priorities?

I think I initially opened this issue b/c I got bit by a correctness bug in one of my scripts. The original intent was to block scope only, but it turns out there are tools that take advantage of probe scoping with initialization in both branches of if/else. So we considered doing a hoist if a variable is initialized in both branches.

It would be great if we could build some consensus about our language design goals so we can properly evaluate this issue against them and come up with a acceptable long term solution.

**Comment by danobi** [comment]
On a technical level, default initialization could be a bit tricky b/c we have so many custom types in the type system. For example, what do we default initialize a timestamp, cgroup path, usym, or ksym to? Forcing initialization side steps this problem.

**Comment by jordalgo** [comment]
> It would be great if we could build some consensus about our language design goals so we can properly evaluate this issue against them and come up with a acceptable long term solution.

Yes, very much agree with coming up with a larger set of language design goals.

> Is having all variables probe scoped really that bad? 

@fbs Makes a good point here. My gut says that the majority of bpftrace programs don't have an issue with only probe/sub-prog scoping but as they get larger/more-complicated I think we want to push toward more expected behavior (with regards to the current most used programming languages). I think simple block scoping (without hoisting) is probably the least surprising and comes with the fewest gotchas. So I think this change falls into the "To prevent programming errors?" bucket. That being said, because this breaks backward compat (for even vetted scripts inside this repo), maybe we should hold off on this change until we can provide variable declarations so we don't have to resort to things like hoisting or default initialization.

**Comment by danobi** [comment]
> maybe we should hold off on this change until we can provide variable declarations so we don't have to resort to things like hoisting or default initialization.

Declarations imply no initialization, so a declaration would be require default values. We can already do initialization like:

```
$v = 123;
if (@condition) {
  $v = 0;
}
```

So if we stick to simple block scoping we would have to modify (for example) tcpconnect.bt from:
```
    if ($inet_family == AF_INET) {
      $daddr = ntop($sk->__sk_common.skc_daddr);
      $saddr = ntop($sk->__sk_common.skc_rcv_saddr);
    } else {
      $daddr = ntop($sk->__sk_common.skc_v6_daddr.in6_u.u6_addr8);
      $saddr = ntop($sk->__sk_common.skc_v6_rcv_saddr.in6_u.u6_addr8);
    }
```
to
```
    $daddr = ntop($sk->__sk_common.skc_v6_daddr.in6_u.u6_addr8);
    $saddr = ntop($sk->__sk_common.skc_v6_rcv_saddr.in6_u.u6_addr8);
    if ($inet_family == AF_INET) {
      $daddr = ntop($sk->__sk_common.skc_daddr);
      $saddr = ntop($sk->__sk_common.skc_rcv_saddr);
    }
```

Which is somewhat inefficient. But at least correct.

**Comment by jordalgo** [comment]
@danobi I guess I was thinking that we could attempt to statically analyze (without condition evaluation) if a variable was used before it was initialized. But maybe that also moves us back into tricky/unexpected territory e.g.

```
int32 $var;
while (condition that will never be true) {
  $var = 1;
}
print(($var)):
```

We could limit it to cases where we know for sure and error out otherwise. Maybe under the hood this still requires default values but I was hoping we could avoid junk/un-optimal initializations.

**Comment by fbs** [comment]
> While I think looking at other languages is useful to see what's been done and how it played out, I think we should be careful to start from first principles here, as we are somewhat in language design. Contrasted to syntax where I think it's less important to innovate.

My point with the python example was more that `if/for/` **not** 'starting' a new scope isn't entirely weird and imo works quite well, in a dynamic language at least.  I think that, with some form of hoisting, it could work well for bpftrace as well.

> It would be great if we could build some consensus about our language design goals so we can properly evaluate this issue against them and come up with a acceptable long term solution.

👍 . A direction/scope of the language and what it tries to solve as a guideline will be really helpful.

**Comment by jordalgo** [comment]
https://github.com/bpftrace/bpftrace/pull/3367
