### ISSUE TITLE
Can't use subprograms from multiple probes

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3021]
The BPF verifier requires that all defined subprograms are used by the main program.

Our current approach involves appending all subprograms into `.text`, whether they are used by a given probe or not. This means that if a script contains multiple probes, each with their own subprograms, the verifier will reject it.

### What reproduces the bug?
```
BEGIN
{
  @map[0] = 1;
  print(len(@map))
}
END
{
  print(len(@map))
}
```

```
Attaching 2 probes...

Error log: 
number of funcs in func_info doesn't match number of subprogs
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

ERROR: Error loading program: BEGIN
```

The easy fix for `len()` would be to simply merge duplicate subprograms into a single `len()` subprogram.
However, we will also need to implement a proper fix for #2955.

libbpf encountered this same problem previously: https://lore.kernel.org/netdev/5f4f311d37ba8_5f3982088@john-XPS-13-9370.notmuch/T/

**Comment by ajor** [comment]
@viktormalik How much of the BpfProgram logic will remain when we complete the libbpf migration? Do you think libbpf will be able to solve this issue for us?

**Comment by viktormalik** [comment]
> The BPF verifier requires that all defined subprograms are used by the main program.
> 
> Our current approach involves appending all subprograms into `.text`, whether they are used by a given probe or not. This means that if a script contains multiple probes, each with their own subprograms, the verifier will reject it.

Ah, so we would need to copy just the required symbols, not the entire `.text`. That sounds tricky as there may be relative offsets which would have to be fixed.

> @viktormalik How much of the BpfProgram logic will remain when we complete the libbpf migration? Do you think libbpf will be able to solve this issue for us?

Yes, it will solve the issue completely as all of the relocations code will go away. I'll put a higher priority on that work.

**Comment by viktormalik** [comment]
What we could do here is emit subprograms into special sections named e.g. `.text.<probe-name>` and then transform the relevant section into `.text` for the given probe in `BpfProgram`.

That should be fairly easy to implement and should temporarily mitigate this issue until we fully move to libbpf.

**Comment by jordalgo** [comment]
>  e.g. .text.<probe-name> and then transform the relevant section into .text for the given probe in BpfProgram.

QQ: should it be probe id? I think you can have multiple of the same probe name right (different preds) ?

I can try to take a look a fixing this issue if folks point me in the right direction :)

**Comment by viktormalik** [comment]
> > e.g. .text. and then transform the relevant section into .text for the given probe in BpfProgram.
> 
> QQ: should it be probe id? I think you can have multiple of the same probe name right (different preds) ?
> 
> I can try to take a look a fixing this issue if folks point me in the right direction :)

I'd use the section name for the given probe (with the `.text` prefix), have a look at the `get_section_name_for_probe` function.

**Comment by jordalgo** [comment]
@viktormalik I might need another pointer :) - I was able to get the temp solution that @ajor mentioned where I just merge the len functions but when trying to put the len subprogram into anything but the ".text" section I ran into this error:
```
[WARN] libbpf: sec 's_BEGIN_1': program 'map_len_cb' is static and not supported
ERROR: Failed to compile: The produced ELF is not a valid BPF object
```
This seems to be a requirement for libbpf: https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L3696C9-L3696C15

This all happens before BpfProgram is invoked. I'm sure I'm just missing something.

**Comment by viktormalik** [comment]
Damn, yeah, I forgot that we're loading the created ELF with libbpf now:
https://github.com/bpftrace/bpftrace/blob/master/src/bpfbytecode.cpp#L15

This may be quite tricky to do, I'm wondering if it is possible to tell libbpf to ignore certain sections. Maybe we could mark them as not containing instructions? This is still a temporary workaround until full libbpf-based loading lands.

**Comment by jordalgo** [comment]
Ah ok. Let's loop in @anakryiko to see if he has any suggestions.

> This is still a temporary workaround until full libbpf-based loading lands.
Is there anything I can do to help unblock libbpf-based loading?

**Comment by viktormalik** [comment]
> Is there anything I can do to help unblock libbpf-based loading?

Not at the moment. It's a lot of work since we need to significantly rework the way we do probe expansion. I believe I'm finally on the right track so some preparation PRs should appear next week. Then, your reviewing help will be much appreciated :-)

**Comment by anakryiko** [comment]
if you are using libbpf to load ELF file, libbpf will take care of only using subprograms that are used by main BPF program. So it all works very naturally. If you are running into some problems, then you are not letting libbpf do its full job. Can someone summarize what's being done by bpftrace vs libbpf, so we can pin down where things go wrong?

**Comment by viktormalik** [comment]
> if you are using libbpf to load ELF file

This is currently WIP but it will take some time to land so we wanted to workaround this issue in the meantime.

> Can someone summarize what's being done by bpftrace vs libbpf, so we can pin down where things go wrong?

Sure, the current (simplified) bpftrace workflow is the following:
1. Generate ELF in which probes go into custom sections and subprograms go into `.text`.
2. Use `bpf_object__open_mem` for the ELF. This is currently used only to discover maps in the program.
3. For each probe, take the corresponding custom section and *the entire* `.text` and pass it to `bpf_prog_load`. This is where the error from the issue description happens as `.text` may contain subprogs for other probes, too.

The plan is to replace point 3 by calling `bpf_object__load` which should resolve the problem but as I mentioned, it's not a straightforward thing to do and will take some time. For the meantime, my idea was to store subprogs in per-probe sections (e.g. `.text.<probename>` and transform them into `.text` for each probe in point 3 but `bpf_object__open_mem` doesn't seem to like such sections.

**Comment by anakryiko** [comment]
@viktormalik yes, libbpf enforces that all subprograms live strictly in .text. There are two (rather hacky, but it's temporary, right?) ways around this:

1) libbpf ignores all the sections that start with ".debug_" (presumably that's DWARF sections), so instead of `.test.<probename>` you can do `.debug_text.<probename>` (or something along those lines)

2) you can maybe make each subprog into its own "entry program" (i.e., section `?kprobe/<subprog>`). Given you use libbpf just to discover maps, it should be fine. Question mark marks it as non-autoloadable by default.

Would any of that work?

**Comment by viktormalik** [comment]
Both would, many thanks! I'm slightly in favor of option 1, @jordalgo do you still have time to look at implementing this? Thanks!

**Comment by jordalgo** [comment]
@viktormalik Yes, let me give it a shot this week. I wanna get better at this part of the codebase. I'll call for help as needed 📞

**Comment by jordalgo** [comment]
Still struggling with this. For example, even if I set the section for the simple map `len` function to `.debug_text` then I get a relocation error when we call `bpf_object__open_mem`
```
[DEBUG] libbpf: sec '.rels_BEGIN_1': relo #2: insn #17 against '.debug_text'
[WARN] libbpf: prog 'BEGIN': bad map relo against '.debug_text' in section '.debug_text'
```

**Comment by jordalgo** [comment]
> you can maybe make each subprog into its own "entry program" (i.e., section ?kprobe/<subprog>). Given you use libbpf just to discover maps, it should be fine. Question mark marks it as non-autoloadable by default.

Tried this too outside of bpftrace in a raw bpf.c file loaded by libbpf and got the same bad map relo error. It also doesn't like when I try to make entry programs static.

**Comment by viktormalik** [comment]
Is the error happening on `bpf_object__open_mem`?

**Comment by viktormalik** [comment]
Ah sorry, I see the answer in one of your previous comments. It looks like we cannot resolve this in another way that moving to libbpf loading. Good news is I've the work almost done, I'm opening the first PR today.

**Comment by viktormalik** [comment]
Dropping the 0.21 milestone from this one as #3233 introduces a user-friendly error and the issue should get resolved by moving to libbpf-based loading.

**Comment by jordalgo** [comment]
This was fixed here: https://github.com/bpftrace/bpftrace/pull/3285
