### ISSUE TITLE
Add printf "%v" specifier to print structures, like in Golang (or as in GDB's print command)

### ISSUE THREAD

**Issue by karim-manaouil** [bpftrace/bpftrace#3036]
### Is your feature request related to a problem? Please describe.

Very often, when debugging kernel code, we want to print and observe the values 
of the different fields making up a structure. Specifying them one by one
in a printf statement is possible, but very tedious.

In Golang, doing `fmt.Printf("%v", struct_ptr)` will print all the members and 
their values.

In GDB, we can also doing something similar using the `p` command that can print
the values of C structures. 

something similar can be implemented for bpftrace, leveraging BTF.

### Describe the solution you'd like

With BTF, we know the exact definition of C structures, the offsets into the members
and their types. That could be leveraged to automatically print the values of the
members of the structure.

### Describe alternative solutions or features you've considered
We can write tedious printf statements listing every possible field.
If it's `task_struct`, or `struct perf_event`, then good luck!

**Comment by viktormalik** [comment]
We already support printing structs via the `print()` function. Is that sufficient for you?

**Comment by karim-manaouil** [comment]
@viktormalik that's correct! The reason I misses that is because I didn't use the asterisk (*) to dereference the pointer and it kept printing the value of the pointer. I just realised that I have to use the asterisk. Thanks!
