### ISSUE TITLE
Probe listing incorrect for BEGIN/END probes

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3057]
```
# bpftrace -l 'BEGIN'
special::
# bpftrace -l 'END'
special::
```

**Comment by ikruglov** [comment]
@ajor, can you please help me to understand what is expected output?

**Comment by ajor** [comment]
What I was thinking when I opened this issue was probably:
```
# bpftrace -l 'BEGIN'
BEGIN
# bpftrace -l 'END'
END
```

But it's probably not something people will ever use and was only really for completeness. It might conflict with your other changes in #3111 (which are definitely more useful), so maybe we just close this one

**Comment by ikruglov** [comment]
ok. closing :-)

**Comment by ikruglov** [comment]
ahm... I don't have permission it seems.
