### ISSUE TITLE
RFC: Logging Updates

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#3102]
Currently, we have 6 different log flavors (all with varying degrees of use and for varying purposes):

- `DEBUG` (used 1 time)
- `INFO` (used 3 times - one of those times is wrong and another is in a unit test)
- `WARNING` (used a lot) 
- `ERROR` (used a lot) 
- `FATAL` (used a lot)
- `BUG` (used 17 times)

At the moment, it seems like `FATAL` and `BUG` are used interchangeably and `ERROR` is sometimes used like a `WARNING` and other times like `FATAL` (calling `exit` right after). There are also plenty of uses of `std::cout` and `std::cerr` - sometimes nested inside `bt_verbose` checks.

**UPDATED Proposal in a comment below.**

So this is an RFC to re-work and codify these logging flavors. Here is the outdated proposal:

- `INFO`: log info to the user regardless of log level - like using stdout
- `V1`: log info to the user only if verbose logging is enabled (bt_verbose or -v)
- `V2`: log info to the user only if very verbose logging is enabled (bt_verbose2 or -vv)
- `WARNING`: log info that might affect bpftrace behavior or output but allows the run to continue - like using stderr
- `ERROR`: abort run and log info to indicate that the user did something invalid which caused bpftrace to exit
- `BUG`: abort run and log info to indicate that there is an internal/unexpected issue (not caused by invalid user program code or CLI use)

**Note**: `V1` and `V2` will replace all instances like this:
```
if (bt_verbose) {
    std::cout << "Attaching to " << probe_.funcs.size() << " functions"
              << std::endl;
```

**Comment by viktormalik** [comment]
> So this is an RFC to re-work and codify these logging flavors. Here is the proposal:

I generally like the below but have a few comments.

> * `INFO`: log info to the user regardless of log level - like using stdout

Since this is so sparsely used, I'm wondering if we need it at all (i.e. if we need to print any information to the user in non-verbose mode). I'm sometimes using `INFO` for debugging but `DEBUG` is better for that purpose as it shows the file name and the line number. So, I'm in favor of keeping `DEBUG` instead of `INFO`.

> * `V1`: log info to the user only if verbose logging is enabled (bt_verbose or -v)
> * `V2`: log info to the user only if very verbose logging is enabled (bt_verbose2 or -vv)

I like this, although I think that `bt_verbose2` is used in a single place only. As a matter of fact, it would be good to rethink the semantics of verbosity/debug options (`-v`, `-vv`, `-d`, `-dd`) as I've run into some problems with them when working with libbpf. Perhaps a good topic for the next office hours.

> * `WARNING`: log info that might affect bpftrace behavior or output but allows the run to continue - like using stderr
> * `ERROR`: abort run and log info to indicate that the user did something invalid which caused bpftrace to exit

Requiring `ERROR` to immediately exit will require significant updates to the semantic analyser as it tends to collect and print all errors at once. With the above, you'd probably have to file the errors as warnings and issue just a single `LOG(ERROR)` at the end. I'd prefer having two different flavors, say `ERROR` and `ABORT`, although `ABORT` should probably prefix the message with `ERROR: ...` to keep consistency in user-facing output.

> * `BUG`: abort run and log info to indicate that there is an internal/unexpected issue (not caused by invalid user program code or CLI use)
> 
> **Note**: `V1` and `V2` will replace all instances like this:
> 
> ```
> if (bt_verbose) {
>     std::cout << "Attaching to " << probe_.funcs.size() << " functions"
>               << std::endl;
> ```

**Comment by jordalgo** [comment]
>  I'm sometimes using INFO for debugging but DEBUG is better for that purpose as it shows the file name and the line number. So, I'm in favor of keeping DEBUG instead of INFO.

We're defining what levels come with file name and line number so that could apply to INFO but I'm fine using DEBUG instead of INFO. But yeah, I agree that neither will probably get used much.

>  I like this, although I think that bt_verbose2 is used in a single place only. As a matter of fact, it would be good to rethink the semantics of verbosity/debug options (-v, -vv, -d, -dd) as I've run into some problems with them when working with libbpf. Perhaps a good topic for the next office hours.

I agree with all of this. Let's get rid of verbose2 entirely. And yes, great discussion for next office hours.

> Requiring ERROR to immediately exit will require significant updates to the semantic analyser as it tends to collect and print all errors at once. With the above, you'd probably have to file the errors as warnings and issue just a single LOG(ERROR) at the end. I'd prefer having two different flavors, say ERROR and ABORT, although ABORT should probably prefix the message with ERROR: ... to keep consistency in user-facing output.

Ah, good point about the semantic analyzer. I guess in the guidelines we can just specify that if you use `LOG(ERROR)` it should eventually lead to program termination via `LOG(ABORT)`.

**Comment by jordalgo** [comment]
Updated proposal:

- `DEBUG`: log info to the user regardless of log level - like using stdout (comes with file and line number)
- `V1`: log info to the user only if verbose logging is enabled (bt_verbose or -v) Note: -vv will be deleted as it's only used in two places in one file.
- `WARNING`: log info that might affect bpftrace behavior or output but allows the run to continue - like using stderr
- `ERROR`: log info to indicate that the user did something invalid which will (eventually) cause bpftrace to exit via `ABORT`. It's possible that there a multiple errors that need to get logged to the user.
- `ABORT`: abort run and log info to indicate that the user did something invalid which caused bpftrace to exit
- `BUG`: abort run and log info to indicate that there is an internal/unexpected issue (not caused by invalid user program code or CLI use)

**Comment by ajor** [comment]
How about `VERBOSE` instead of `V1` if we're only having one verbosity level?

> * `ERROR`: log info to indicate that the user did something invalid which will (eventually) cause bpftrace to exit via `ABORT`.

Does "exit via `ABORT`" mean something special or can `ERROR` just eventually trigger a clean exit?

Otherwise I like it!

**Comment by viktormalik** [comment]
> Does "exit via `ABORT`" mean something special or can `ERROR` just eventually trigger a clean exit?

+1 here, we don't need to explicitly recommend exiting via `ABORT`, IIUC, `ABORT` = (error message + `exit()`).

**Comment by jordalgo** [comment]
> How about VERBOSE instead of V1 if we're only having one verbosity level?

I prefer V1 mostly because VERBOSE is well... verbose. I was also thinking of changing WARNING to just WARN. V1 leaves the door open to have additional levels but it also implies there are multiple, which there won't be (in this proposal). I'm torn.

> +1 here, we don't need to explicitly recommend exiting via ABORT, IIUC, ABORT = (error message + exit()).

JC, what is the use case for logging errors that end in a clean exit? Or am I just getting hung up on the word "clean" - we should be calling `exit(1)` right? But yeah, I'm fine with just calling `exit(1)` at some point after `LOG(ERROR)` instead of `LOG(ABORT)`.

**Comment by viktormalik** [comment]
> JC, what is the use case for logging errors that end in a clean exit? Or am I just getting hung up on the word "clean" - we should be calling `exit(1)` right? But yeah, I'm fine with just calling `exit(1)` at some point after `LOG(ERROR)` instead of `LOG(ABORT)`.

Yes, I meant using e.g. `exit(1)` instead of `LOG(ABORT)`.

**Comment by jordalgo** [comment]
Closing this as it's been mostly resolved over multiple PRs:
https://github.com/bpftrace/bpftrace/pull/3164
https://github.com/bpftrace/bpftrace/pull/3091
https://github.com/bpftrace/bpftrace/pull/3202
