### ISSUE TITLE
Race condition in map loop for BPF_MAP_TYPE_PERCPU_HASH

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#3117]
```
BEGIN {
  $i = 0;
  while ($i < 100) {
    @m[1] += 1;
    $i++;
    if ($i == 100) {
      exit();
    }
  }
}

END {
  for ($kv : @m) {
    print(($kv));
  }
  clear(@m);
}
```

This script seems to always exit with the correct output, namely: `(1, 100)`.

However if you use the `count()` function instead of `+=1`, which is functionally equivalent, I often see this as the output: `(1,0)`.

My guess is that because the map used for `count` is `BPF_MAP_TYPE_PERCPU_HASH` vs `BPF_MAP_TYPE_HASH` used for the `+=` operation, there is some issue there but that's as far as I got.

**Comment by ajor** [comment]
It looks like the problem occurs when the `BEGIN` and `END` probes run on different CPUs:
```
BEGIN {
  $i = 0;
  while ($i < 100) {
    @m[cpu] = count();
    $i++;
  }
}

END {
  for ($kv : @m) {
    print((cpu, $kv));
  }
  clear(@m);
}
```

Same CPU, correct result:
```
(15, (15, 100))
```

Different CPU, wrong result:
```
(57, (59, 0))
```

**Comment by jordalgo** [comment]
> Maybe https://github.com/bpftrace/bpftrace/issues/3126 is the solution for this bug as well? When reading a per-cpu map value, collect data from all CPUs.

Yeah that makes sense. I'll try to pick up that task soon (if no one beats me to it).

**Comment by jordalgo** [comment]
This is fixed here: https://github.com/bpftrace/bpftrace/pull/3189
