### ISSUE TITLE
Implicit casts from per-CPU integers into regular integers

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3126]
Example usage:
```
tracepoint:syscalls:sys_enter_read { @c = count(); }
interval:s:1 { if (@c > 100) { exit() } }
```

Current behaviour:
```
ERROR: Type mismatch for '>': comparing 'count' with 'int64'
interval:s:1 { if (@c > 100) { exit() } }
                  ~~~~~~~~~
```

Per-CPU maps help to improve the performance of writes, but it is difficult to read their values. Currently they can only be aggregated and read in userspace, so people often fall back to using regular, non-per-cpu maps instead.

It'd be useful if we provided a mechanism to read the aggregated values of per-cpu maps from within BPF.

The `bpf_map_lookup_percpu_elem` helper can be used to look up a Per-CPU map's value from a different CPU.

A cast from a per-CPU integer to a regular integer could be done with this pseudo-code:
```
@percpu = count();
$int = 0;
$int += bpf_map_lookup_percpu_elem(@percpu, 0, 0); // CPU 0
$int += bpf_map_lookup_percpu_elem(@percpu, 0, 1); // CPU 1
$int += bpf_map_lookup_percpu_elem(@percpu, 0, 2); // CPU 2
$int += bpf_map_lookup_percpu_elem(@percpu, 0, 3); // CPU 3
...
```

**Comment by janca-ucdavis** [comment]
That overhead could get pretty gnarly with repeated per-element access and a lot of CPUs.  I'd like to throw another idea out there I've been chewing on for a while - what about a "reduce" function that could fold percpu maps or arrays into a non-percpu map in bulk, asynchronously?

I do a lot of things with BPF that are borderline map/reduce, and this would help a lot with getting data into structures fast (percpu) and then doing further reduction for summary stats.  Right now at probe time I often push data into both per-CPU maps and not.

**Comment by jordalgo** [comment]
@janca-ucdavis I also wish there was some internal BPF utility to do something like this but I think the issue for bpftrace (as you alluded to) is the asynchronous part of this operation. If we're inside a BPF prog, which is non sleepable (as pretty much all bpftrace BPF programs are) then we can't queue some work async and wait for it before continuing to execute the rest of the program. So even if we do some kind of reduce, it would have to be sync and that's just doing the same iteration over all cpus to gather the values.

**Comment by janet-campbell** [comment]
I'm specifically interested in an async reduce - it would be fine for my case if all of this happened from userland.  I'm thinking of a "printinto" command, where you could do something like:

printinto(@globalmap, @mypercpumap)

or ideally, have a way to apply a per-element conditional.

I work around most other async func issues (like print() and clear()) by using an old dtrace trick - explicit double buffering with a "bank" variable to point at one of two sets of maps.  Flip bank in the timer thread, print and clear the other buffer.  In cases like this I don't need synchronous behavior.  It would be handy to have a "are all async ops done?" function.

If anything I want to see more async functions, not less.

**Comment by jordalgo** [comment]
@janet-campbell I think I understand what you mean with the "bank" variable but I'd still be curious to see some example scripts if you're willing to share.

**Comment by janet-campbell** [comment]
Most of my stuff uses m4 macros to automate this but it gets expressed like this.  I usually move data through structures in a phased way, where the writers and the readers aren't operating on the same resources:

`BEGIN
{
  // current buffer to receive data
  @rxb_rwstats = 0;
}

kprobe:something
{   
    $deltat = something;
    $logdeltat = macro_log2_8throot($deltat);
    
    if (@rx_b) { @stats_1[$fsuid] = stats($deltat);
                 @hstats_1[$fsuid] = lhist($logdeltat, 0, 193, 1); }
    else       { @stats_0[$fsuid] = stats($deltat);
                 @hstats_0[$fsuid] = lhist($logdeltat, 0, 193, 1); }
}


interval:s:15
{
    // the current buffer becomes the transmit buffer
    $txb_rwstats = @rxb_rwstats;

    // flip the active buffer to the other one
    @rxb_rwstats = (1 - $txb_rwstats);

    printf("\nBEGIN\n");

    if ($txb_rwstats) { print(@stats_1); clear(@stats_1); }
                 else { print(@stats_0); clear(@stats_0); }
}
`

We found this to be a good approach with dtrace when dealing with systems that may get heavily loaded or when sample loss must be kept to a minimum.  A variant on this uses multiple phases to make sure all the writers are flipped over before printing and clearing the data buffers, another uses overlapping buffers to hold medium term information that may not be able to be cleaned up (this was a workaround for the lack of LRU maps).

**Comment by danobi** [comment]
@janca-ucdavis 

> That overhead could get pretty gnarly with repeated per-element access and a lot of CPUs

At least with the implementation in the current PR, you basically have to opt into inline folding. Either by an explicit cast, iteration over a `map[int]count` map, or use in a binop expression. If you need async semantics, then do the expensive stuff in a different probe. If you need it inline, well, you'll have to pay for it.

Does that address your concerns?

**Comment by danobi** [comment]
>  A variant on this uses multiple phases to make sure all the writers are flipped over before printing and clearing the data buffers

That kinda sounds like an RCU use case. Interesting for sure, and possibly worth exploring.

**Comment by janet-campbell** [comment]
Yes, that does sound fine - I do think that anything that synchronously operates on multiple pieces of data should make sure that is explicitly called out, but it's definitely a useful feature to add.

> printinto(@aglobalmap, @mypercpumap)

Just FYI, my project with these kind of operations in mind is to build a streaming k-means clustering implementation, to automatically group multidimensional data points.  I'm still chewing on how to do it most efficiently and coming to terms with bpf/bpftrace, so I may say a dumb thing or two along the way.

**Comment by danobi** [comment]
> Yes, that does sound fine - I do think that anything that synchronously operates on multiple pieces of data should make sure that is explicitly called out, but it's definitely a useful feature to add.

Valid point. I tend to lean towards that philosophy, but IMHO it's a balance between simplicity (a core goal of bpftrace) and perhaps unnecessary verbosity.

> 
> > printinto(@aglobalmap, @mypercpumap)
> 
> Just FYI, my project with these kind of operations in mind is to build a streaming k-means clustering implementation, to automatically group multidimensional data points. I'm still chewing on how to do it most efficiently and coming to terms with bpf/bpftrace, so I may say a dumb thing or two along the way.

No worries! Seems like you're pushing the limits of bpftrace - we appreciate that kind of feedback a lot. It'll help guide us on what to work on.

**Comment by jordalgo** [comment]
+1 to what @danobi said. These are super interesting use cases for bpftrace that we want to become more familiar with and help support.

**Comment by jordalgo** [comment]
Closing this as 'sum', 'count', 'min', 'max', and 'avg' all now can be implicitly casted.
