### ISSUE TITLE
Synchronise probe start times

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3128]
### Problem

Probes are currently attached one-at-a-time, roughly in the order that they're declared in a script (with some [extra ordering logic](https://github.com/bpftrace/bpftrace/blob/b3a6d9a28f63ec0146d49fe4f68d6d5c2b5d96fe/src/bpftrace.cpp#L1172-L1177) that I'm not sure is 100% correct).

That means that this script may print many lines of "a" before a single "b" appears:
```
tracepoint:syscalls:sys_enter_read { print("a") }
tracepoint:syscalls:sys_exit_read { print("b"); exit() }
```

```
Attaching 2 probes...
a
a
a
a
b
```

Reversing the order of the probes, the script would always print "b" then exit without printing a single "a":
```
tracepoint:syscalls:sys_exit_read { print("b"); exit() }
tracepoint:syscalls:sys_enter_read { print("a") }
```

These staggered start times can be confusing for users.

### Solution

It would be nice to provide the option to synchronise probe start times.

We don't have any way to attach them all at the same time, so one alternative solution is to add an implicit predicate to every probe which references a global variable:
```
/ is_started == true /
```

Then just toggle the variable to true from userspace once all probes are attached and ready to go.

There is some small overhead to adding a predicate to every probe, so we could make this a configurable setting.

**Comment by amscanne** [comment]
I believe that this is hashed out in #1157, and there's a specific problem and proposal there. (It is essentially the same solution, except the builtin in named `active` rather than `is_started`). It may be worthwhile to dup to that issue and join the threads.

**Comment by jordalgo** [comment]
Closing to discuss the proposed solution in https://github.com/bpftrace/bpftrace/issues/1157
