### ISSUE TITLE
llvm assertion failure triggered by DIBuilderBPF::createFunctionDebugInfo

### ISSUE THREAD

**Issue by fvdlfvdl** [bpftrace/bpftrace#3131]
This happens with HEAD as of this writing, but, looking at the code, would have happened for a while, since the DIBuilder debuginfo code was introduced:

With LLVM assertions enabled, DIBuilderBPF::createFunctionDebugInfo triggers the following assert when debuginfo is generated for a probe:

assertion failed at llvm-project/llvm/lib/IR/DIBuilder.cpp:822 in DILocalVariable
 *llvm::DIBuilder::createParameterVariable(DIScope *, StringRef, unsigned int, DIFile *, unsigned int, DIType *, bool, DINode::DIFlags, DINodeArray): ArgNo &&  "Expected non-zero argument number for parameter"

This happens because createFunctionDebugInfo attempts to create debug info for two variables, the first of which is the return value (int64), the second is the first (and only) parameter, the context pointer. (int8 *) The types of these are defined as:

```
SmallVector<Metadata *, 2> types = { getInt64Ty(), getInt8PtrTy() };
```

This array is correctly passed to createSubroutineType, which is then used to generate function debug info.

However, then it attemps to create debug info for both of these, creating "var0" for the return value, and "var1" for the argument parameter:

```
  std::string prefix("var");
  for (size_t i = 0; i < types.size(); ++i) {
    createParameterVariable(subprog,
                            prefix + std::to_string(i),
                            i,
                            file,
                            0,
                            (DIType *)types[i],
                            true);
  }
```

This then triggers the assertion, since the 3rd argument to createParameterVariable (ArgNo) is supposed to be 1..N. The value 0 is reserved for auto (local) variables by LLVM DiBuilder. So, without assertions enabled, it just creates a local variable called "var0", which has the same type as the return value, and (correctly) a parameter called "var1".

I don't think DiBuilder has a notion of named return values or anything like that, so it seems to me that the code should just call createParameterVariable for the only argument (int8 *), and leave the return value alone - it is already included in the debug info for the function.

**Comment by jordalgo** [comment]
@fvdlfvdl Thanks for the bug report. Do you mind sharing your cmake, make, and bpftrace commands that trigger this assertion? As well as the llvm version.

**Comment by fvdlfvdl** [comment]
@jordalgo Thanks for th comment. My configuration is a little unusual - it's basically llvm @ HEAD, with LLVM_ENABLE_ASSERTIONS set, so you can't reproduce this with any plain LLVM release - the assertion is not compiled in.

Having said that, if you inspect the code, the issue is easily spotted, and it's clear that the bpftrace code doesn't correctly use the LLVM interface. The call to ```DIBuilder::createParameterVariable```  at ```src/ast/dibuilderbpf.cpp:44``` will pass 0 for ArgNo in the first iteration of the loop.

LLVM has had an assertion in ```DIBuilder::createParameterVariable``` to make sure that ArgNo is not 0 here for a long time: https://github.com/llvm/llvm-project/blob/main/llvm/lib/IR/DIBuilder.cpp#L822 (since 2015, by looking at the git history).

The documentation for this interface can be found here: https://llvm.org/doxygen/classllvm_1_1DIBuilder.html#afa7c4efcb5c40c8527c13759f10ef5ed

It states:

```
ArgNo is the index (starting from 1) of this variable in the subprogram parameters. 
```

So, this is not easily reproducible in the sense that you need an LLVM debug environment to trigger it. However, code inspection shows it's a bug. Not a serious one, since the incorrect debuginfo for a BPF probe will currently not cause any issues (that I'm aware of), but a bug nonetheless.

**Comment by jordalgo** [comment]
@fvdlfvdl Thanks for the detailed explanation. If I understand correctly, I think this is the fix you were suggesting: https://github.com/bpftrace/bpftrace/pull/3133
