### ISSUE TITLE
Logging errors results in abnormal termination (abort)

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3163]
Since #3091, errors which trigger bpftrace to terminate do so by calling `abort()` and core-dumping. This is a bad user experience.

#### Repro

Trigger an error:
```
# bpftrace -e 'kretprobe:_raw_spin_lock {}'
Attaching 1 probe...
ERROR: kretprobe:_raw_spin_lock can't be used as it might lock up your system.
Aborted
```

#### Expected Behaviour

bpftrace should exit by returning from `main` with a non-zero error code.

**Comment by jordalgo** [comment]
@ajor Is the only issue here is the calling of `abort`? Can we just call `exit(1)` instead in the `LOG(FATAL)` path as this is dedicated to user errors?

**Comment by ajor** [comment]
I think throwing an exception from the `LOG(FATAL)` path and catching it in `main()` would be more future-proof: it'll perform call destructors for all living objects so any RAII cleanups will run, and it'll work almost without changes for bpftrace-as-a-library (we can create a no-throwing wrapper around the library later).
