### ISSUE TITLE
Specialize non-associative maps to be BPF_MAP_TYPE_ARRAY

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#3186]
### Is your feature request related to a problem? Please describe.

Consider:
```
$ sudo ./build/src/bpftrace -e 'kprobe:zswap_swapon { @x++ }'
```

It generates the following code:
```
$ sudo bpftool prog dump xlated id 120
int64 kprobe_zswap_swapon_1(int8 * ctx):
   0: (b7) r1 = 0
   1: (7b) *(u64 *)(r10 -16) = r1
   2: (bf) r2 = r10
   3: (07) r2 += -16
   4: (18) r1 = map[id:69]
   6: (85) call __htab_map_lookup_elem#248656
   7: (15) if r0 == 0x0 goto pc+1
   8: (07) r0 += 56
   9: (b7) r1 = 1
  10: (15) if r0 == 0x0 goto pc+2
  11: (79) r1 = *(u64 *)(r0 +0)
  12: (07) r1 += 1
  13: (7b) *(u64 *)(r10 -8) = r1
  14: (bf) r2 = r10
  15: (07) r2 += -16
  16: (bf) r3 = r10
  17: (07) r3 += -8
  18: (18) r1 = map[id:69]
  20: (b7) r4 = 0
  21: (85) call htab_map_update_elem#260176
  22: (b7) r0 = 0
  23: (95) exit
```

Notice all the htab_map calls. This is extra and unnecessary overhead.

### Describe the solution you'd like

We can specialize non-associative maps in https://github.com/bpftrace/bpftrace/blob/0d06553e98833fa014b514bd620701623ea65607/src/ast/passes/codegen_llvm.cpp#L3534 to use BPF_MAP_TYPE_ARRAY. The verifier will rewrite ARRAY accesses to plain memory access -- no helper calls required.

### Describe alternative solutions or features you've considered

Do nothing :P

**Comment by ajor** [comment]
Done in #3300
