### ISSUE TITLE
Can't trace a uprobe set with perf: `ioctl(PERF_EVENT_IOC_SET_BPF): Invalid argument`

### ISSUE THREAD

**Issue by gukoff** [bpftrace/bpftrace#3198]
### What reproduces the bug? Provide code if possible.

On Ubuntu 22.04 (running on Virtualbox), create a new probe with `perf`. For example:

```bash
$ sudo perf probe -f -x /lib/x86_64-linux-gnu/libc.so.6 glibc:pthread_cond_timedwait=pthread_cond_timedwait
```

This probe is visible to `bpftrace` both as a tracepoint and a rawtracepoint: 

```bash
$ sudo ./bpftrace -l | grep pthread_cond_timedwait
rawtracepoint:pthread_cond_timedwait
tracepoint:glibc:pthread_cond_timedwait
```

But trying to trace this probe fails:

```bash
$ sudo ./bpftrace -e 'tracepoint:glibc:pthread_cond_timedwait { printf("%s\n", comm); }'
Attaching 1 probe...
ioctl(PERF_EVENT_IOC_SET_BPF): Invalid argument
ERROR: Error attaching probe: tracepoint:glibc:pthread_cond_timedwait

$ sudo ./bpftrace -e 'rawtracepoint:pthread_cond_timedwait { printf("%s\n", comm); }'
Attaching 1 probe...
ERROR: Probe does not exist: rawtracepoint:pthread_cond_timedwait
```

### `bpftrace --info` output

This is the output for the last AppImage bpftrace. But the older bpftrace v0.14.0 has the same behavior.

```
System
  OS: Linux 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024
  Arch: x86_64

Build
  version: v0.20.4
  LLVM: 17.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: no
  get_func_ip: yes
  jiffies64: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: no
  uprobe_multi: no
  raw_tp_special: yes
  iter: yes
```

**Comment by ajor** [comment]
I can repro this on my machine.

I've got to ask though: what's the use-case for this functionality? Why not just use a uprobe / USDT?

**Comment by gukoff** [comment]
> what's the use-case for this functionality? Why not just use a uprobe / USDT?

In this particular case, it's merely for convenience. I wanted to reuse the tracepoints already set when tracing with perf.

Do you know why this error happens and how the perf tracepoints are different from the built-in ones? I'm curious

**Comment by ajor** [comment]
I don't know, sorry - I've never tried this before.

As a guess, the perf tracepoints might be using an `int3` instruction to trigger an interrupt at the specified point in the same way that uprobes and USDTs do.

Kernel tracepoints are statically compiled in rather than dynamically injected at runtime, so they behave much more like a regular function call.

**Comment by ajor** [comment]
Closing in favour of the duplicate issue #3447 where some solutions are proposed.
