### ISSUE TITLE
Clarify install & supported distros

### ISSUE THREAD

**Issue by travisdowns** [bpftrace/bpftrace#3210]
I'm on Ubuntu 22.04, which until a month ago was the most recent TLS distribution.

There is a `bpftrace` package for my distro but it is a bit out of date, so some programs don't compile (e.g., because there have been changes in the block layer structures).

So when I follow the installation instructions, [it says](https://github.com/bpftrace/bpftrace/blob/master/INSTALL.md#1904-and-newer):

> For 19.04 and newer, please see the [regularly exercised Dockerfile](https://github.com/bpftrace/bpftrace/blob/master/docker/Dockerfile.ubuntu) for documentation on how to build bpftrace on Ubuntu.

The dockerfile just has a few simple build steps. However, it's not clear how I should use it:

 1) If I build bpftrace inside the docker container, it will be orphaned in there and I pull it out, it won't run because of needing very new glibc version, etc.
 2) If I just follow the same steps outside, it currently doesn't build on Ubuntu 22.04 (which you can see if you change `ubuntu:devel` `ubuntu:22.04` in the Dockerfile, it no longer builds even in docker.

**Comment by danobi** [comment]
Hi Travis, thanks for the report. I switched from `ubuntu:devel` -> `ubuntu:22.04` like you suggested and I see libbpf related errors.

It looks like ubuntu 22.04 only has libbpf v0.5: https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/libbpf0_0.5.0-1_amd64.deb.html

bpftrace now needs at least libbpf 1.0 to build. For better or for worse, bpf is a fast moving ecosystem. It was too difficult to make progress and still support all the older dependency versions (esp b/c libbpf broke compat going to 1.0). We should probably have cmake error out more cleanly.

If you need to user a newer bpftrace on an older distro, we recommend using the appimage: https://github.com/bpftrace/bpftrace/blob/master/INSTALL.md#appimage-install . From user PoV, it is a static binary. Trunk is currently broken (see https://github.com/bpftrace/bpftrace/pull/3051 for discussion), but upstream nixpkgs folks are on it.

The release appimage should work ok: https://github.com/bpftrace/bpftrace/releases/tag/v0.20.4

**Comment by ajor** [comment]
> There is a `bpftrace` package for my distro but it is a bit out of date, so some programs don't compile (e.g., because there have been changes in the block layer structures).

@travisdowns Are you talking about bpftrace scripts (e.g. [the tools](https://github.com/bpftrace/bpftrace/tree/master/tools)) not compiling because of kernel changes?

If that's the case then a more recent bpftrace executable won't help - you'd be better off using an older version of the script which was designed to work on your kernel version, e.g. https://github.com/bpftrace/bpftrace/blob/master/tools/old/biosnoop.bt
