### ISSUE TITLE
Attaching to non-existing uprobes fails

### ISSUE THREAD

**Issue by viktormalik** [bpftrace/bpftrace#3235]
#3155 broke scripts which use probes attaching to multiple uprobes when some of the target functions do not exist. Previously, we would silently ignore such attach points, now bpftrace fails with:
```
ERROR: Could not resolve symbol: ...
```

Among others, this also breaks a couple of tools (`ssllatency.bt`, `sslsnoop.bt`, `threadsnoop.bt`). CI didn't catch that since we're just parsing the tool script and do not try to attach them. This will be fixed by #3203.

While this is clearly wrong and we need to fix it, I realized that we're doing different things for uprobes and kprobes:
- for uprobes, we call `resolve_uname` and if the function doesn't exist, we silently ignore it,
- for kprobes, we always try to attach and if that fails, we issue a warning for probes with multiple attach points and continue.

I'm not sure if this is on purpose but I think that it'd be good to unify this. The options are:
1. Silently ignore non-existing attach points for both kprobes and uprobes (possibly for kfuncs, too).
2. Always issue a warning for non-existing attach points.
3. Only show warnings in verbose mode.
4. Add a CLI option or a config option to show the warnings.

All in all, any of the above options will affect the existing scripts including the tools shipped in the main repo. Either the uprobe-based tools will start showing warnings or the kprobe-based tools will stop showing them.

Personally, I'm in favor of option (3) as I find the warnings needlessly polluting the default output of tracing tools. For instance, some tools are designed in a way that there's always just one kprobe existing (b/c it was renamed in the kernel at some point) and therefore will always show the warning.

**Comment by jordalgo** [comment]
This sort of thing does fall squarely in our guidelines for `LOG(WARNING)`: "log info that might affect bpftrace behavior or output but allows the run to continue; like using stderr". 

We already have a half of option 4 (a CLI optioin), so we could extend it to be a config option for scripts which may do a lot of attaching. 

I'm on the fence. I agree that it does pollute output but for new bpftrace users, swallowing these warnings/errors might confuse them as it potentially affects script behavior. So I guess I'm between option 3 and 4.

**Comment by danobi** [comment]
With my reliability hat on, I'd say I feel strongly about warning by default. We really do not want users to think they've successfully attached to a probe when in reality they haven't.

To help with the noise, I think it'd make sense to provide a way to silence the warnings. Not sure what form that would take yet though. Maybe a config? It could make sense to acknowledge in script source that they will be trying to attach to non-existent probes.

**Comment by viktormalik** [comment]
> With my reliability hat on, I'd say I feel strongly about warning by default. We really do not want users to think they've successfully attached to a probe when in reality they haven't.
> 
> 
> 
> To help with the noise, I think it'd make sense to provide a way to silence the warnings. Not sure what form that would take yet though. Maybe a config? It could make sense to acknowledge in script source that they will be trying to attach to non-existent probes.

Now thinking about it again, I think that you're right. We don't want to omit the warning by default as it would obscure potentially unexpected behavior from users.

It does make sense to let users decide to silent the warning, though, presumably mainly for long-term used scripts (such as the shipped tools). So, a config option makes sense, I'll add one.
