### ISSUE TITLE
CommandLine Error

### ISSUE THREAD

**Issue by AnonymousRonin** [bpftrace/bpftrace#3266]
I get the following error when attmepting to run hashcat, clinfo

: CommandLine Error: Option 'openmp-ir-builder-optimistic-attributes' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
Aborted

have llvm-17.0.6 (preinstalled)
clang -17 (preinstallled)

Error occured after attmpting llvm-project and to upgrade llvm.  Tied deleing vendors to just one (openCL), Tried every other suggestion I found with no luck. Any help would be appreciated.

**Comment by viktormalik** [comment]
Looks like a duplicate of #1855.

**Comment by ajor** [comment]
Closing as duplicate
