### ISSUE TITLE
Addressing LIBBPF_OPTS vs. clang warnings vs. C++ struct initialisation

### ISSUE THREAD

**Issue by hhoffstaette** [bpftrace/bpftrace#3276]
As continuation of https://github.com/bpftrace/bpftrace/commit/65a08f4c38505d327862d52404be85469168966a the following is a request for ideas on how to best fix the C++ warnings caused by libbpf's LIBBPF_OPTS macro. This turned out to be a surprisingly deep swamp of C/C++/compiler-specific details, so sorry for the long-winded explanation.
I'm willing to make the PR but for now am just looking for the least bad option. :)

First is the inconsistent use of `DECLARE_LIBBPF_OPTS` vs. `LIBBPF_OPTS`. The former is a deprecated value and simply #defined to `LIBBPF_OPTS`, so replacing those few instances is trivial.

Second, the problem itself:
```
/tmp/bpftrace/src/bpffeature.cpp:62:5: warning: missing field 'attempts' initializer [-Wmissing-field-initializers]
   62 |     LIBBPF_OPTS(bpf_prog_load_opts, opts);
      |     ^
/usr/include/bpf/libbpf_common.h:70:3: note: expanded from macro 'LIBBPF_OPTS'
   70 |                 };                                                          \
      |                 ^
/tmp/bpftrace/src/bpffeature.cpp:134:3: warning: missing field 'log_true_size' initializer [-Wmissing-field-initializers]
  134 |   LIBBPF_OPTS(bpf_btf_load_opts,
      |   ^
/usr/include/bpf/libbpf_common.h:70:3: note: expanded from macro 'LIBBPF_OPTS'
   70 |                 };                                                          \
      |                 ^
```
(ad.inf.)

These all have the same underlying problem: the [LIBBPF_OPTS macro](https://github.com/libbpf/libbpf/blob/42065ea6627ff6e1ab4c65e51042a70fbf30ff7c/src/libbpf_common.h#L64) uses memset to zero out the declared struct (which in itself can be problematic in C++, see e.g. [here](https://stackoverflow.com/questions/2837854/initializing-an-object-to-all-zeroes), which does not impress at least clang-18 in the slightest due to the .sz designated initializer, and so it helpfully reminds us to also initialize all the other members.

This seems to be a cause of much grief everywhere. Example discussions with no useful conclusions are e.g.:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82283
https://github.com/llvm/llvm-project/issues/68933
https://github.com/llvm/llvm-project/issues/56628

None of this really helps us, so let's focus on what we *could* change.

- I don't see changing the upstream libbpf declaration itself as an option, given it targets C (*not* C++) and works fine at runtime. Also libbpf already has enough problems.

- Instead of using memset I tried to rewrite the macro to use an explicit struct initializer `{}` or `{0}`. This fixed nothing.

- bpftrace already has one instance of warning suppression [here](https://github.com/bpftrace/bpftrace/blob/19df2b1bf8fc018f7a0b4695473c36a5d8752980/src/btf.cpp#L571C9-L571C75) - this "fixes" the problem at the cost of having to be sprinkled across the code at every call site. Not great.

- Maybe reusing the original `LIBBPF_OPTS` in a _Pragma-handling wrapper would work?
```
#define BPFTRACE_LIBBPF_OPTS(TYPE, NAME, ...) \
  _Pragma("GCC diagnostic push") \
  _Pragma("GCC diagnostic ignored \"-Wmissing-field-initializers\"") \
  LIBBPF_OPTS(TYPE, NAME, __VA_ARGS__) \
  _Pragma("GCC diagnostic pop")
```
Stick this into `bpffeature.h`, search & replace to use the new macro and voilà! Silence. :shushing_face: 
So this would work with the least amount of risk/churn.

Would this be an acceptable fix?

**Comment by hhoffstaette** [comment]
Btw this is not a bug but I cannot change the category.

**Comment by hhoffstaette** [comment]
Excellent, thank you - I'll make a PR soon.
For what it's worth I also tried `#undef`ining the existing LIBBPF_OPS and then redefining it so that all call sites could remain unmodified, but ultimately decided against this because I couldn't find a good way to prevent accidental include order problems or redefinition errors.
Using our own variant is the simplest thing I could come up with.

**Comment by viktormalik** [comment]
> Excellent, thank you - I'll make a PR soon.

Great, thanks!

> For what it's worth I also tried `#undef`ining the existing LIBBPF_OPS and then redefining it so that all call sites could remain unmodified, but ultimately decided against this because I couldn't find a good way to prevent accidental include order problems or redefinition errors. Using our own variant is the simplest thing I could come up with.

No, let us not redefine libbpf's macros please, that sounds very error-prone.

**Comment by hhoffstaette** [comment]
So it turns out the first cut worked with clang but NOT with gcc because [reasons](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78657) :angry: 
However after some fiddling I found that this seems to only affect the push/pop pragmas, and removing them allows this to work after all. Seems acceptable to me.
