### ISSUE TITLE
Warning: Unknown Attribute 'preserve_access_index' Ignored and BTF Redefinition Conflict

### ISSUE THREAD

**Issue by vishalc-ibm** [bpftrace/bpftrace#3284]
#### Description:
When running a `bpftrace` script with the `#include "vmlinux.h"` directive, multiple warning messages are generated, and the process takes an unusually long time to complete. The specific errors observed are:

```
./vmlinux.h:5:46: warning: unknown attribute 'preserve_access_index' ignored [-Wunknown-attributes]
./vmlinux.h:126539:1: note: when applied to this declaration
WARNING: Cannot take type definitions from BTF since there is a redefinition conflict with user-defined types.
```

This issue is particularly observed with structures defined in `vmlinux.h`.

### What reproduces the bug?
1. Ensure the kernel is built without the `CC=clang` option.
2. Run the following `bpftrace` command:
Note: It maybe the case that this reproduces only on Power Architecture. 

```bash
bpftrace -e '#include "vmlinux.h" kprobe:do_task_stat { printf("func:do_task_stat\n"); }'
```

#### Expected Behavior:
The `bpftrace` command should execute without warnings and within a reasonable time frame.

#### Actual Behavior:
- Multiple warnings are generated regarding the unknown attribute `preserve_access_index`.
- Warning about redefinition conflict with user-defined types.
- The command takes an unusually long time to complete (`real 1m44.703s`).

<details><summary>Additional Information [expandable]</summary>

Kernel source for the definition of `struct cpio_data`:
<details><summary>vmlinux.h</summary>

```c
#ifndef BPF_NO_PRESERVE_ACCESS_INDEX 
#pragma clang attribute push (__attribute__((preserve_access_index)), apply_to = record)    // line number 5
#endif
...
struct cpio_data {                               // line number 126539
     void *data;
     size_t size;
     char name[18];
};
```
</details>

<details><summary>include/linux/earlycpio.h</summary>

```c
struct cpio_data {                         
    void *data;
    size_t size;
    char name[MAX_CPIO_FILE_NAME];
};
```
</details>
</details>

#### References:
- [LLVM D69759 Patch](https://reviews.llvm.org/D69759): This patch introduced a new BPF-specific attribute which can be added to struct or union definitions to preserve access indices, but the attribute has no effect if `-g` is not specified.

#### Logs:
```
./vmlinux.h:5:46: warning: unknown attribute 'preserve_access_index' ignored [-Wunknown-attributes]
./vmlinux.h:126539:1: note: when applied to this declaration
WARNING: Cannot take type definitions from BTF since there is a redefinition conflict with user-defined types.
```

Execution Time:
```bash
# time bpftrace -e '#include "vmlinux.h" kprobe:do_task_stat {printf("func:do_task_stat\n");}'
...
./vmlinux.h:5:46: warning: unknown attribute 'preserve_access_index' ignored [-Wunknown-attributes]
./vmlinux.h:126539:1: note: when applied to this declaration
...
WARNING: Cannot take type definitions from BTF since there is a redefinition conflict with user-defined types.
real    1m44.703s
user    1m42.742s
sys     0m0.080s
```

Please let me know if any additional details are required. Thank you for looking into this issue.

### `bpftrace --info` output
<details><summary> # bpftrace --info </summary>

```
System
  OS: Linux 6.10.0-rc2+ #1 SMP Fri Jun 28 
  Arch: ppc64le

Build
  version: v0.20.1
  LLVM: 17.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes
  jiffies64: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: no
  uprobe_multi: no
  raw_tp_special: yes
  iter: yes
```
<details>

<details><summary> libbpf version </summary>

```
# dnf info libbpf
Installed Packages
Name         : libbpf
Epoch        : 2
Version      : 1.4.0
Release      : 2.el10
Architecture : ppc64le
Size         : 586 k
Source       : libbpf-1.4.0-2.el10.src.rpm
Repository   : @System
Summary      : Libbpf library
License      : LGPL-2.1-only OR BSD-2-Clause
Description  : A mirror of bpf-next linux tree bpf-next/tools/lib/bpf directory plus its
             : supporting header files. The version of the package reflects the version of
             : ABI.
```
</details>

**Comment by viktormalik** [comment]
There are multiple things here:
- The warning is generated by Clang which we run to parse the header files (in `ClangParser`). I'm not sure if we'd be able to silent the warning.
- The slow execution is caused by `vmlinux.h` being a huge file and us parsing and visiting every single struct and field inside. This is something that I think we're not able to change.

What comes to mind, though, is a question whether you could use BTF instead of `vmlinux.h` (which is likely generated from BTF anyways). bpftrace can retrieve all the necessary types from BTF and there's no need to include `vmlinux.h` (and therefore run clang) at all. For your case, it'd be running the same script without the `#include "vmlinux.h"` part.

**Comment by vishalc-ibm** [comment]
When I write my own c bpf program which includes `vmlinux.h` and compile it using `clang`, it works like a charm. 
I am able to immediately compile and load.

Now, I can bear with the slow execution, but the issue here, is, when using `bpftrace`, program never loads.

> What comes to mind, though, is a question whether you could use BTF instead of `vmlinux.h` (which is likely generated from BTF anyways). bpftrace can retrieve all the necessary types from BTF and there's no need to include `vmlinux.h` (and therefore run clang) at all.

How does bpftrace compiles the program to bpf assembly internally?

Using `vmlinux.h` is convenient for me, I don't have to go and search for the necessary header files.

**Comment by viktormalik** [comment]
> When I write my own c bpf program which includes `vmlinux.h` and compile it using `clang`, it works like a charm. 
> 
> I am able to immediately compile and load.
> 
> 
> 
> Now, I can bear with the slow execution, but the issue here, is, when using `bpftrace`, program never loads.

Ok, that's interesting, especially since the log you attached doesn't contain any errors, only warnings. Could you please run bpftrace (preferably compiled from the latest master) with the `-v` option?

> 
> 
> 
> > What comes to mind, though, is a question whether you could use BTF instead of `vmlinux.h` (which is likely generated from BTF anyways). bpftrace can retrieve all the necessary types from BTF and there's no need to include `vmlinux.h` (and therefore run clang) at all.
> 
> 
> 
> How does bpftrace compiles the program to bpf assembly internally?

We directly emit LLVM IR and let LLVM handle compilation to BPF bytecode.

> 
> 
> 
> Using `vmlinux.h` is convenient for me, I don't have to go and search for the necessary header files.

The point with bpftrace parsing BTF data is that you don't have to include _anything_. As long as you use normal kernel types, bpftrace will find them for you.

**Comment by vishalc-ibm** [comment]
I collected `trace.log` file 

```
#  bpftrace -v do_task_stat.trace.bt &> trace.log

# grep -Ev "preserve|declaration" trace.log
./vmlinux.h:38:3: error: typedef redefinition with different types ('struct __vector128' vs 'struct __vector128')
/lib/modules/6.10.0-rc2+/build/arch/powerpc/include/uapi/asm/types.h:36:32: note: previous definition is here
./vmlinux.h:98:3: error: typedef redefinition with different types ('struct atomic_t' vs 'struct atomic_t')
/lib/modules/6.10.0-rc2+/build/include/linux/types.h:177:3: note: previous definition is here
./vmlinux.h:102:3: error: typedef redefinition with different types ('struct atomic64_t' vs 'struct atomic64_t')
/lib/modules/6.10.0-rc2+/build/include/linux/types.h:184:3: note: previous definition is here
./vmlinux.h:104:8: error: redefinition of 'list_head'
/lib/modules/6.10.0-rc2+/build/include/linux/types.h:193:8: note: previous definition is here
./vmlinux.h:109:8: error: redefinition of 'hlist_node'
/lib/modules/6.10.0-rc2+/build/include/linux/types.h:201:8: note: previous definition is here
./vmlinux.h:114:8: error: redefinition of 'callback_head'
/lib/modules/6.10.0-rc2+/build/include/linux/types.h:235:8: note: previous definition is here
./vmlinux.h:2777:2: error: redefinition of enumerator 'false'
/lib/modules/6.10.0-rc2+/build/include/linux/stddef.h:11:2: note: previous definition is here
./vmlinux.h:2778:2: error: redefinition of enumerator 'true'
/lib/modules/6.10.0-rc2+/build/include/linux/stddef.h:12:2: note: previous definition is here
./vmlinux.h:2868:8: error: redefinition of 'hlist_head'
/lib/modules/6.10.0-rc2+/build/include/linux/types.h:197:8: note: previous definition is here
./vmlinux.h:13226:3: error: typedef redefinition with different types ('struct rcuref_t' vs 'struct rcuref_t')
/lib/modules/6.10.0-rc2+/build/include/linux/types.h:189:3: note: previous definition is here
./vmlinux.h:34202:3: error: typedef redefinition with different types ('struct __kernel_fsid_t' vs 'struct __kernel_fsid_t')
/lib/modules/6.10.0-rc2+/build/include/uapi/asm-generic/posix_types.h:81:3: note: previous definition is here
./vmlinux.h:73105:3: error: typedef redefinition with different types ('struct __kernel_fd_set' vs 'struct __kernel_fd_set')
/lib/modules/6.10.0-rc2+/build/include/uapi/linux/posix_types.h:27:3: note: previous definition is here
./vmlinux.h:95403:8: error: redefinition of 'ustat'
/lib/modules/6.10.0-rc2+/build/include/linux/types.h:205:8: note: previous definition is here
WARNING: Cannot take type definitions from BTF since there is a redefinition conflict with user-defined types.
```

**Comment by viktormalik** [comment]
Ah, I see. The problem is that we include `linux/types.h` by default (due to some historical and backwards compat reasons) which (naturally) conflicts with `vmlinux.h`.

Anyways, as I mentioned previously, the best and recommended approach is to not include anything and let bpftrace parse type definitions from BTF.
