### ISSUE TITLE
`--dry-run` should not run programs

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3330]
`--dry-run` does cause bpftrace to exit, but only after its probes have fired thousands of times in this example:

```
# bpftrace --dry-run -e 't:sched:sched_switch { @ = count(); }' -d ast

AST after: parser
-------------------
Program
 tracepoint:sched:sched_switch
  =
   map: @
   call: count

[...]

AST after: ReturnPath
-------------------
Program
 tracepoint:sched:sched_switch
  =
   map: @ :: [count]
   call: count :: [count]

Attaching 1 probe...


@: 5396
```

**Comment by viktormalik** [comment]
This is a bit tricky b/c we want to actually attach the probes (to test that they can be attached and potentially see the logs if they cannot). But once a probe is attached, it starts firing (so bpftrace program is "running").

What we can do, though, is that we can minimize the time between attachment and termination so I crafted #3408 to address this. With the above script, I'm getting:
```
# bpftrace --dry-run -e 't:sched:sched_switch { @ = count(); }' -d ast
[...]
Attaching 1 probe...


@: 0
```

**Comment by jordalgo** [comment]
@viktormalik Do you think it would be easy to stop any script output (I'm looking at that empty map at the end)?

**Comment by viktormalik** [comment]
@jordalgo the output from probes should be suppressed already as we do not poll for perf events. It also makes sense to skip printing the map contents at the end, I crafted #3410 to do that. Thanks for the suggestion!
