### ISSUE TITLE
Unable to pass 64bit hex values larger than LLONG_MAX as positional arguments

### ISSUE THREAD

**Issue by mtijanic** [bpftrace/bpftrace#3335]
### What reproduces the bug? Provide code if possible.
```
$ sudo bpftrace -e 'BEGIN {printf("%llx\n", $1);}' 0xffffffffffffffff
stdin:1:25-27: ERROR: $1 used numerically but given "0xffffffffffffffff". Try using str($1).
BEGIN {printf("%llx\n", $1);}
                        ~~
$ sudo bpftrace -e 'BEGIN {printf("%llx\n", $1);}' 0x7fffffffffffffff
Attaching 1 probe...
7fffffffffffffff
```

This is because `is_numeric()` uses `std::stoll` which interprets 0x hex literals as unsigned always, but since it is trying to convert it to signed, it throws an out_of_range exception

Naively, I'd say something like..
```diff
bool is_numeric(const std::string &s)
{
  std::size_t idx;
  try {
    std::stoll(s, &idx, 0);
  } catch (...) {
+    try {
+        std::stoull(s, &idx, 0);
+    } catch(...);
    return false;
  }
  return idx == s.size();
}
```
would make the function behave as expected, but I have no idea if that will break anything else, and/or if it would result in onion peeling and the whole thing failing at the conversion step later. Sorry, I'm not set up to build bpftrace and test.

This would be very useful to have so we can read an address from /proc/kallsyms and feed it as an argument, since most kernel addresses will have the highest bit set.

### `bpftrace --info` output
```
System
  OS: Linux 5.15.0-105-generic #115~20.04.1-Ubuntu SMP Mon Apr 15 17:33:04 UTC 2024
  Arch: x86_64

Build
  version: v0.21.1
  LLVM: 18.1.7
  unsafe probe: no
  bfd: yes
  liblldb (DWARF support): yes
  libsystemd (systemd notify support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: no
  get_func_ip: yes
  jiffies64: yes
  for_each_map_elem: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: no
  uprobe_multi: no
  raw_tp_special: yes
  iter: yes
```

**Comment by jordalgo** [comment]
@mtijanic Thanks for the report and the suggestion. The fix seems a bit more involved but I'll hopefully have a PR up soon. In the meantime, can use `kaddr` to get the kernel address you need? https://github.com/bpftrace/bpftrace/blob/master/man/adoc/bpftrace.adoc#functions-kaddr

**Comment by mtijanic** [comment]
Thanks for the suggestion. I can't use kaddr since the global variable is part of a loaded out of tree module, but I do have a workaround by preprocessing the bpftrace script (which I do anyway), so something like:
```
addr=`sudo grep MySymbolName /proc/kallsyms | awk '{print $1}' | xargs printf "0x%s"`
cat test.bt | cpp -P -DMYSYMBOL_ADDR=$addr $* - | xargs -0 sudo ./bpftrace -e
```
and then in the script, `$MySymbolNamePtr = kptr(MYSYMBOL_ADDR));`

**Comment by jordalgo** [comment]
fixed here: https://github.com/bpftrace/bpftrace/pull/3336
