### ISSUE TITLE
RFC: Methods

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#3361]
Currently, we have multiple, hard-coded functions which take a specific type as an argument: `len`, `clear`, `strcontains `, etc. However, many modern, popular languages support methods on more complex types/objects. So is this something we want to add to **bpftrace**?

Example syntax for maps (this is probably the biggest use case at the moment):
```
@my_map.len();
@my_map.contains(key);
@my_map.clear();
```

This could also work for strings, stacks, time, etc.
```
str("hello").contains("h");
str("hello").substring(3, 2);

ustack.len();
ustack.setMode(raw);

nsecs.toMicroSeconds();
```

## Pros
- Feels more inline with the direction of modern programming languages
- Method chaining
- I, personally, find it easier to read/grok
- Less hard-coded function names in the parser (less conflicts with user-defined functions)

## Cons
- Strays from BPF C code, which eventually we want to interop with
- We'd have to deprecate the functions that we want to migrate to methods
- Muddies the water in terms of understanding if bpftrace is an object-oriented language
- Limited to internal bpftrace types

Please feel free to add more pros and cons (I'll edit the list) and questions/comments about this direction for the language.

**Comment by danobi** [comment]
I don't really have an opinion yet but FWIW if this is only gonna be for function calls it's basically syntactic sugar. Front end can just transform `@x.contains(key)` into `contains(@x, key)`. So for backwards compat existing stuff should just work. But if you add data mambers it's more different

**Comment by ajor** [comment]
+1

I think methods will clean up the syntax a lot.

The current syntax for `delete()` is pretty janky - it appears as if it's looking up a value in a map before passing it to the delete function: `delete(@mymap[0])`.

**Comment by jordalgo** [comment]
@ajor - Should we close this RFC in favor of the UFCS one? Seems like folks were pretty split on adding "methods" at least in this form.

**Comment by ajor** [comment]
Closing in favour of #3499
