### ISSUE TITLE
Support an optional size parameter for `path()` builtin

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#3376]
### Is your feature request related to a problem? Please describe.
Right now values returned by `path()` are all sized to BPFTRACE_MAX_STRLEN. This is bad in the big string world (see #3371) as now paths will not fit inside scratch variables, as scratch variables go on the stack and are subject to the 512B bpf stack limit.

### Describe the solution you'd like
We should support an optional size parameter just like `str()` so users have the option to clamp path sizes.

### Describe alternative solutions or features you've considered
Alternatively, they could assign the value to a map which does not have size limitations.

**Comment by jordalgo** [comment]
Makes sense to me.

**Comment by ZhangYet** [comment]
@danobi @jordalgo  Are there any unit tests for the `path` helper?

**Comment by jordalgo** [comment]
Sorry, saw this before I asked for tests on the PR :) 

Here are the unit tests: https://github.com/bpftrace/bpftrace/blob/master/tests/semantic_analyser.cpp#L3167
And the runtime tests: https://github.com/bpftrace/bpftrace/blob/d93aae09689ccb8fcbbf230f8d7b3831cb12b881/tests/runtime/call#L469

**Comment by ZhangYet** [comment]
@jordalgo thanks! I will do it after work.

**Comment by ZhangYet** [comment]
```shell
====================
bpftrace --info:
====================
System
  OS: Linux 6.10.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000
  Arch: x86_64

Build
  version: v0.21.0-111-g9996
  LLVM: 18.1.8
  unsafe probe: no
  bfd: yes
  liblldb (DWARF support): yes
  libsystemd (systemd notify support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes
  jiffies64: yes
  for_each_map_elem: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: yes
  uprobe_multi: yes
  raw_tp_special: yes
  iter: yes

[==========] Running 2 tests from 1 test cases.

[----------] 2 tests from call
[ RUN      ] call.path
[  TIMEOUT ] call.path
        Command: /home/dantezy/Repos/bpftrace/build/src/bpftrace -ve 'kfunc:filp_close { if (!strncmp(path(args.filp->f_path), "/tmp/bpftrace_runtime_test_syscall_gen_read_temp", 49)) { printf("OK\n"); exit(); } }'
        Timeout: 5
        Current output: AST node count: 18
Attaching 1 probe...
Attaching kfunc:vmlinux:filp_close
__BPFTRACE_NOTIFY_PROBES_ATTACHED



[ RUN      ] call.path_in_unsupported_kfunc
[       OK ] call.path_in_unsupported_kfunc
[----------] 2 tests from call

[==========] 2 tests from 1 test cases ran. (10247 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 tests, listed below:
[  TIMEOUT ] call.path
make[3]: *** [tests/CMakeFiles/runtime_tests.dir/build.make:70: tests/CMakeFiles/runtime_tests] Error 1
make[2]: *** [CMakeFiles/Makefile2:1802: tests/CMakeFiles/runtime_tests.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1809: tests/CMakeFiles/runtime_tests.dir/rule] Error 2
make: *** [Makefile:817: runtime_tests] Error 2
```

The runtime test `call.path` failed on master(9996177e80f66e1d991f960fa9eb39c221ed7f45). 

I built and ran the test as:

```shell
cmake -B ./build -DBUILD_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=1
make -C ./build -j$(nproc)
 cd build
 sudo TEST_FILTER=call.path make runtime_tests
 ```

**Comment by ZhangYet** [comment]
I think I found the reason why the test failed on my machine:

Since kernel 021a160abf62 ("fs: use __fput_sync in close(2)") , the `close` syscall wouldn't invoke `flip_close` any more.

And d11ae1b16b0a ("selftests/bpf: Fix d_path test") also modify the kernel selftest. 

Maybe we should raise a new issue to fix the runtime test on some newer kernels?
