### ISSUE TITLE
Split output on `-lv`, to `stdout` and `stderr`

### ISSUE THREAD

**Issue by phmarek** [bpftrace/bpftrace#3379]
Output of `bpftrace -lv` is split up to `stdout` and `stderr`.

This is bad, because `bpftrace -lv kfunc:vmlinux:*mount | less` will show a list of `kfunc` and a list of parameters, without any association being possible.

### What reproduces the bug?

```
$ sudo strace bpftrace -vl 'kfunc:vmlinux:kern_unmount' | less
kfunc:vmlinux:__detach_mounts
kfunc:vmlinux:__fsnotify_vfsmount_delete
kfunc:vmlinux:__ia32_sys_fsmount
kfunc:vmlinux:__ia32_sys_listmount
...
    struct vfsmount * mnt
    void * arg
    int retval
    struct tomoyo_request_info * r
```

`strace` confirms that:

```
write(1, "kfunc:vmlinux:kern_unmount\n", 27kfunc:vmlinux:kern_unmount
) = 27
write(2, "    struct vfsmount * mnt", 25    struct vfsmount * mnt) = 25
write(2, "\n", 1
)
```

A possible workaround is
```
$ sudo bpftrace -vl 'kfunc:vmlinux:*mount*' 2>&1 | less
```

but that's not really nice, all that output should go to `stdout` by default.

### `bpftrace --info` output

```
$ bpftrace --info
ERROR: bpftrace currently only supports running as the root user.
$ sudo bpftrace --info
System
  OS: Linux 6.8.12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.8.12-1 (2024-05-31)
  Arch: x86_64

Build
  version: v0.21.2
  LLVM: 17.0.6
  unsafe probe: no
  bfd: no
  liblldb (DWARF support): no
  libsystemd (systemd notify support): no
...
```

**Comment by ZhangYet** [comment]
It looks this simple PR(#3383) can fix this problem. But I'm not quite understand why choose `LOG(V1) << "    " << param;`  when implementing `list_probes`.

**Comment by danobi** [comment]
Probably b/c the output was gated on `-v` (verbose flag). So verbose log level was chosen. Probably didn't think too hard about it - the motivation for this fix makes a lot of sense.
