### ISSUE TITLE
Support cgroup_path as a mapkey

### ISSUE THREAD

**Issue by boryas** [bpftrace/bpftrace#3421]
### Is your feature request related to a problem? Please describe.
cgroup_path is awesome! :)
```
$ sudo bpftrace -e 'BEGIN { print(cgroup_path(cgroup)) }'
Attaching 1 probe...
unified:/user.slice/user-1000.slice/session-3.scope
```

but it can't be a key in a map :(
```
$ sudo bpftrace -e 'BEGIN { @[cgroup_path(cgroup)] = 42; }'
Attaching 1 probe...
^C

BUG: [/build/bpftrace/src/bpftrace-0.21.0/src/mapkey.cpp:150] invalid mapkey argument type
zsh: IOT instruction  sudo bpftrace -e 'BEGIN { @[cgroup_path(cgroup)] = 42; }'
```

### Describe the solution you'd like
Do the same trick of storing the cgroup id and resolving it in userspace when printing map keys. This would obviously be subject to races, but technically so is the current solution for printf, IIUC. The races for maps would be wider, since they get printed at exit, but I still think it would be useful, at least for stable cgroup hierarchies.

### Describe alternative solutions or features you've considered
* `$cg_name = str(curtask->cgroups->dfl_cgrp->kn->name);` but it runs in bpf so it can't recurse/iterate and doesn't get the whole hierarchy
* writing my script in libbpf
* parsing the bpftrace output and resolving cgroup ids then

**Comment by ZhangYet** [comment]
@boryas I have tried resolved this issue. But it's beyond my ability now. It's not easy to use `cgroup_path` as a mapkey, since `cgroup_path` will generate a `cgroup_path_t` struct, which contains `cgroup_id` and `cgroup_path_id`. `cgroup_path_id` always changes.

More details can refer to: https://github.com/bpftrace/bpftrace/pull/3438#issuecomment-2361477135

**Comment by jordalgo** [comment]
I'm going to close as it's probably something we don't need to support now that we can iterate over maps (and just use the cgroup id as the key) e.g.
```
BEGIN {
  @mp[cgroup] = 42; exit(); 
}

END { 
  for ($kv : @mp) { 
    print((cgroup_path($kv.0), $kv.1)); 
   } 
}
```
