### ISSUE TITLE
Tuple variable reassignment is broken when it contains strings of different sizes

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#3439]
I believe this is happening because we're not comparing the type size of these two assignments properly (or at all) in semantic_analyser. I noticed this when working on https://github.com/bpftrace/bpftrace/pull/3390/

### What reproduces the bug? Provide code if possible.

Notice how the integer after "hi" is 0 in both cases.

```
$ sudo bpftrace -e 'BEGIN { $a = (1, "hi", 5); print(($a)); $a = (1, "asdfasdfasdfasdfasdfasdf", 10); print(($a)); exit(); }'
Attaching 1 probe...
(1, hi, 0)
(1, asdfasdfasdfasdfasdfasdf, 10)
```

```
sudo bpftrace -e 'BEGIN { $a = (1, "hiasdfasdfasdfasdfasdf", 5); print(($a)); $a = (1, "hi", 10); print(($a)); exit(); }'
Attaching 1 probe...
(1, hiasdfasdfasdfasdfasdf, 5)
(1, hi, 0)
```

**Comment by ajor** [comment]
Has this been fixed by #3443? The example scripts are working now at least
