### ISSUE TITLE
Add a config variable to use symbol addresses instead of LLDB location resolution

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#3493]
### Is your feature request related to a problem? Please describe.

We saw an issue where LLDB was generating a uprobe location that was falling in between two instructions. This is bad and can cause memory corruption in the targeted process if the uprobe is attached (via use of the `--unsafe` flag).

### Describe the solution you'd like

Create a [config variable](https://github.com/bpftrace/bpftrace/blob/master/man/adoc/bpftrace.adoc#config-variables) that will default to using LLDB location resolution but provides the option of disabling this and using symbol addresses for all probes.

### Describe alternative solutions or features you've considered

Deciding not to go with this option: https://github.com/bpftrace/bpftrace/pull/3481

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
