### ISSUE TITLE
New delete syntax conflicts with multi-delete syntax

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3496]
Related to #3472.

Multi-delete syntax:
```
@[10] = 100;
delete(@[10], @[11]); // delete element with key 10 and element with key 11
```

New delete syntax:
```
@[10] = 100;
delete(@, 10); // delete element with key 10

@key = 10;
delete(@, @key); // !!! does not delete element with key 10 - this instead triggers the multi-delete variant
```

#### Complete repro
This script should work with the new syntax, but that would require deleting the multi-delete syntax:
```
# bpftrace -e 'BEGIN { @[10] = 100; @val = 10; delete(@, @val); exit(); }'
stdin:1:33-41: ERROR: Argument mismatch for @: trying to access with no arguments when map expects arguments: 'int64'
BEGIN { @[10] = 100; @val = 10; delete(@, @val); exit(); }
                                ~~~~~~~~
```

**Comment by jordalgo** [comment]
Maybe a temporary solution for this could be to assume the user is utilizing the new delete API if the first argument is a reference to a map that has keys but the expression does not.

**Comment by ajor** [comment]
I'd rather we just fix it properly in all situations, and the easiest way to do that is (IMO) to fully remove the multi-delete syntax. It's pretty new (only appeared in the latest release: 0.21) so it's unlikely that many people are depending on it yet.

**Comment by jordalgo** [comment]
> I'd rather we just fix it properly in all situations, and the easiest way to do that is (IMO) to fully remove the multi-delete syntax. It's pretty new (only appeared in the latest release: 0.21) so it's unlikely that many people are depending on it yet.

Ah ok. I thought we wanted to keep it but deleting it is just fine with me!

**Comment by danobi** [comment]
Dang, unfortunate. So the ambiguity is only when the second arg is a keyed map, eg `@foo[$bar]` b/c deleting a scalar map doesn't make sense eg (`@foo`). Can we warn in that case that the semantics have changed? If anyone is using it, then they're in for a really confusing time if it's a silent change.

**Comment by jordalgo** [comment]
@danobi - You can delete scalar maps. It's equivalent to calling `clear`.

>  Can we warn in that case that the semantics have changed? 

If we're removing the ability to pass multiple maps to `delete` then the user will get an error that explains the new API - you could make a case for adding additional information to that error message but TBH, I think it's pretty self explanatory: "delete() expects a map for the first argument and a key for the second argument e.g. `delete(@my_map, 1);"

**Comment by danobi** [comment]
Ah, right. So `@foo[$bar]` resolves to a value (and not a map), so they get a good error.

**Comment by danobi** [comment]
The first arg would have had to be a keyed map for it to have been a multi-delete. New delete API requires first arg to be unkeyed map. So I _think_ it's unambiguous if we remove multi-delete. ie. no existing code can get silently get new semantics.

**Comment by jordalgo** [comment]
> The first arg would have had to be a keyed map for it to have been a multi-delete.

Why is that? This seems to work for me `BEGIN { @s = 2; @a[1] = 1; @b[2] = 2; delete(@s[1], @a[1], @b[2]); exit(); }`
Though as you pointed out here, it's a bit weird: https://github.com/bpftrace/bpftrace/issues/3498

**Comment by danobi** [comment]
Argh, right. Unless it's a scalar map. In which case a second argument was not valid anyways.

**Comment by ajor** [comment]
Is this what's being suggested?
```
@a = 1;
@b[0] = 0;
@c[0] = 0;

delete(@a, @b[0]); // multi-delete
delete(@c, @b[0]); // new delete syntax
```

I think that this is very confusing, personally. It's impossible to tell what a `delete` function call will do without looking at the complete program. Removing the multi-delete syntax seems like the only way to resolve this with sane semantics to me.

Maybe this needs to be done over a longer period of time to avoid changing the semantics under existing scripts. e.g. remove the multi-delete syntax in v0.22 and then re-introduce the new delete syntax in v0.23.

**Comment by jordalgo** [comment]
> Maybe this needs to be done over a longer period of time to avoid changing the semantics under existing scripts. e.g. remove the multi-delete syntax in v0.22 and then re-introduce the new delete syntax in v0.23.

How does the staggered release help users. They'll have to migrate they're multi-delete calls to single calls for a soon-to-be-deprecated syntax then migrate again when we eventually kill the old syntax. Also I feel like holding off on introducing the new delete syntax would hold up adding `has_key` because then there would be a signature mismatch.

**Comment by ajor** [comment]
I think I might have misunderstood the discussion above. The staggered release suggestion was to ensure we could differentiate between the multi-delete and the new syntax, but I think the point being made was that we can do that already.

I just want to ensure that we don't support both multi-delete and the new syntax at the same time. If we immediately remove the multi-delete syntax that'd be fine too.

This I'd be ok with:
```
@a = 1;
@b[0] = 0;
@c[0] = 0;

delete(@a, @b[0]); // multi-delete - compilation error
delete(@c, @b[0]); // new delete syntax works
```

**Comment by jordalgo** [comment]
Multi-delete was removed here: https://github.com/bpftrace/bpftrace/pull/3506
