### ISSUE TITLE
Optimise `len()` by using `bpf_map_sum_elem_count` kfunc

### ISSUE THREAD

**Issue by ajor** [bpftrace/bpftrace#3511]
The `len()` function currently works by iterating over all elements in a map. The kernel provides a kfunc `bpf_map_sum_elem_count` which does the same, more efficiently.

It looks like this kfunc has a simple interface, so it might be a good candidate for our first kfunc. @viktormalik

**Comment by ZhangYet** [comment]
Cool! Maybe it can also resolve the https://github.com/bpftrace/bpftrace/issues/3308

But also we need to consider the older version kernels.

**Comment by ajor** [comment]
Yeah it'll definitely help to make the problems in #3308 less common, but they'll still be there for people writing their own for-loops (and older kernels, as you say)

**Comment by viktormalik** [comment]
> It looks like this kfunc has a simple interface, so it might be a good candidate for our first kfunc. @viktormalik

Hm, I already looked at it but I somehow assumed that the map pointer passed to the function must be a dynptr which has to be acquired and then released via different kfuncs (which is what I wanted to avoid). But looking again now, it looks like when the map is defined in the same BPF object, it could be passed directly. I'll have a look into this.

> I have written a `bpf_map_sum_elem_count` demo yesterday. And on x86_64 platform, I found the asm use `call -0x1` to invoke this kfunc, which is a indirect call. So I wonder if this is platform related?

It's not, `call -0x1` is just a placeholder. It will be replaced (relocated) by a correct BTF ID of the `bpf_map_sum_elem_count` symbol on the target machine.

**Comment by batu3H** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
