### ISSUE TITLE
RFC: Resize integer scratch variables

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#3518]
Currently (on master) this is allowed:
```
$x = (uint32)2; $x = 1;
```

However this causes a semantic analyzer error:
```
$a = 1; $x = (uint32)2; $x = $a;
...
Type mismatch for $x: trying to assign value of type 'int64' when variable already contains a value of type 'uint32'
```

This is because `1` is a literal and we can statically determine if the literal fits inside the uint32 type. However a variable might be resolved at runtime so we don't know how big it will actually be (e.g. it's coming from an `args` field).

For strings, we automatically take the max, even for variables e.g. this is fine:
```
$a = str(args.filename); $x = "hi"; $x = $a;
```

And the size of $a will be set to `max_strlen`. 

I propose we do the same thing for int scratch variables and resize when needed to provide the most flexibility. This begs the question: should a right hand cast dictate the type of the variable on the left? My current feeling is **no** and that the only thing that should indicate a concrete variable type is with a let declaration e.g. `let $x: int32;`.

**Comment by danobi** [comment]
> might be resolved at runtime so we don't know how big it will actually be (e.g. it's coming from an args field).

I think we know all sizes at compile time. Even those from `args`. Otherwise `sizeof()` would not work (and it does).

**Comment by ajor** [comment]
Local variables in BpfScript do not have any complicated type inference from a user's point of view: they take the type of their first assignment and that's it. I'm against complicating that.

`string` is a single, variable length type, while `int32` and `int64` are two distinct types so the logic shouldn't really be compared. A way around this would be to introduce a variable-sized integer type, but I'm not sure exactly how that would work.

For comparison, C++ and Rust both work the way we currently do, where a variable's type is inferred from the first usage:
```
[auto|let mut] x = 123;      // type inferred as int32
x = 123412341234;            // can't assign int64 to int32
```

**Comment by jordalgo** [comment]
Perhaps what I'm craving is the option to not error in the cases of possible integer overflow especially if we're not doing a good job a statically analyzing if integer expressions are compatible (e.g. my example above `$a = 1; $x = (uint32)2; $x = $a;`).

Continuing with @ajor's C++/Rust example, it depends on the compiler flags used if integer overflow causes an error. Maybe bpftrace could also add this as a config option e.g. "integer_overflow". Though that may be just as much trouble as simply adding a cast lol.

**Comment by danobi** [comment]
I agree with Alastair, I don't think we want to complicate / complex-ify type inference any more than necessary. I'm also skeptical of a language change to deal with this. What we really want is better static analysis, right? One obvious (but very suboptimal way) is to not desugar in parser - just propagate a new AssignVarCompoundStatement into the AST.

Or in semantic analyser we could reach into the assignment expr and guess if it's a compound binop. But that feels fragile to me.

**Comment by jordalgo** [comment]
Closing for now. I agree with @danobi that we probably just want better static analysis (or a config to determine how we handle integer overflow)
