### ISSUE TITLE
Add the ability for users to not print maps at the end of program exit

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#3545]
bpftrace currently prints all maps/globals by default upon program termination and the only way to prevent this is to explicitly call `clear` on these maps in an `END` probe (though it doesn't work for scalar maps).

It would be great if users didn't have to write `clear()` multiple times if they don't want to print these maps.

### Describe the solution you'd like

My current preference would be a config variable e.g. `print_maps_on_exit`, which would default to true to not disturb the current behavior, which is great for one-liners.

### Describe alternative solutions or features you've considered

Another option would be a command line arg but I think we probably want to keep these to minimum. Any other suggestions are welcome!

**Comment by amscanne** [comment]
I've picked this up in #3547 as a learning exercise. The suggestions seemed reasonable to me, but I'm no expect so feedback welcome.
