### ISSUE TITLE
Make `--info` more compact

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#3554]
### Is your feature request related to a problem? Please describe.

`bpftrace --info` is getting quite long. Would be good to make better use of screen real estate. Maybe multiple key: value entries per line?

One thing to make sure of is to keep runtime test feature parser in sync: https://github.com/bpftrace/bpftrace/blob/acc409c19be21d2a09077b2bd0c098a5babbea1b/tests/runtime/engine/runner.py#L124-L155

**Comment by fbs** [comment]
I quite like it being verbose but something like `--info -v` to get verbose would also be ok

**Comment by danobi** [comment]
@fbs Oh, I don't mean reduce amount of information. I meant make the information more visually compact. So something like:

```
Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
```

to

```
Kernel helpers
  probe_read: yes          probe_read_str: yes
  probe_read_user: yes     probe_read_user_str: yes
  probe_read_kernel: yes   probe_read_kernel_str: yes
```

**Comment by sikehish** [comment]
I'd like to take this up :)

**Comment by fbs** [comment]
@danobi I like it not being compact. Find it easier to read through / grep. But  its not a big deal either.

Maybe we should have a json output for it, as a 'machine' format? That way the test parser can also be simpler.

**Comment by danobi** [comment]
@fbs if we use my example, grepping continues to work. And personally I don't find having two aligned columns any more visually difficult to parse. JSON output / machine output is reasonable, although that's not the problem I'm trying to solve.

Perhaps I should've led with this, but the issue I'm trying to solve is that `bpftrace --info` doesn't fit in one terminal screen anymore. And since we ask for `--info` output to report bugs, it adds friction to bug reporting process. If you work on remote servers a lot, then scrollback on things like tmux while trying to copy/paste is kinda klunky. I think reducing bug report friction is quite important.

Perhaps long term we want something like https://bun.sh/blog/bun-report-is-buns-new-crash-reporter. That's quite slick but it seems like a good amount of work, including a website with a backend.

**Comment by danobi** [comment]
@fbs any objections before we let @sikehish have a go at this?

**Comment by fbs** [comment]
oh sorry missed it.  

Let's give it a go, I don't use --info that often anyway.

go for it @sikehish 👍

**Comment by sikehish** [comment]
> oh sorry missed it.
> 
> Let's give it a go, I don't use --info that often anyway.
> 
> go for it @sikehish 👍

Sure!

**Comment by danobi** [comment]
@sikehish do you still plan on working on this?

**Comment by sikehish** [comment]
> @sikehish do you still plan on working on this?

Hi @danobi. Apologize for the delay. Yes I will be working on it, just had a few other commitments. Will be getting this done ASAP. Thank you for the reminder.

**Comment by danobi** [comment]
Sweet! We have develop docs here: https://github.com/bpftrace/bpftrace/blob/master/docs/developers.md

In general we recommend the nix build: https://github.com/bpftrace/bpftrace/blob/master/docs/nix.md#dont-use-nix-to-build-but-rather-only-manage-dependencies. It's most likely to work.

**Comment by sikehish** [comment]
> Sweet! We have developer docs here: https://github.com/bpftrace/bpftrace/blob/master/docs/developers.md
> 
> In general we recommend the nix build: https://github.com/bpftrace/bpftrace/blob/master/docs/nix.md#dont-use-nix-to-build-but-rather-only-manage-dependencies. It's most likely to work.

Hi @danobi . Apologize for the delay. I've raised a PR #3616 . Let me know if any changes are to be made :))
