### ISSUE TITLE
Verifier error caused by llvm transformation

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#3603]
### What reproduces the bug? Provide code if possible.
The script below triggers this verifier error:
```
...
39: (85) call bpf_map_update_elem#2   ; R0=scalar()
40: (07) r6 += 16                     ; R6_w=ctx(off=16)
41: (79) r7 = *(u64 *)(r6 +0)
dereference of modified ctx ptr R6 off=16 disallowed
```

```

BEGIN { @args[1] = (uint64)1; }
tracepoint:syscalls:sys_enter_kill
{
  // other if statements don't cause this error
  if (strcontains(comm, "fb-oomd")) {
    @test[args.pid] = 1;
  }
  // using this variable in place of the two lookups
  // below doesn't trigger the error
  // $x = @args[1];
  if (args.pid == @args[1]) {
    print((1));
  }
  if (args.pid == @args[1]) {
    print((1));
  }
}
```

@4ast believes it can be fixed by this though I'm not sure where to place that yet in the codegen.
`__attribute__((preserve_static_offset))`
https://clang.llvm.org/docs/AttributeReference.html#preserve-static-offset

### `bpftrace --info` output

System
  OS: Linux 5.19.0
  Arch: x86_64

Build
  version: v0.21.0-1b7c
  LLVM: 17.0.4
  bfd: yes
  liblldb (DWARF support): yes
  libsystemd (systemd notify support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes
  jiffies64: yes
  for_each_map_elem: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  Kernel DWARF: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  fentry: yes
  kprobe_multi: yes
  uprobe_multi: no
  iter: yes

**Comment by eddyz87** [comment]
> @4ast believes it can be fixed by this though I'm not sure where to place that yet in the codegen.
__attribute__((preserve_static_offset))

The `preserve_static_offset` attribute works by replacing getelementptr+load/store with `llvm.bpf.getelementptr.and.{load,store}` intrinsic function calls. These calls are preserved trough the optimization passes and are unrolled as gep+load/store just before machine code generation. E.g. see test cases `llvm/test/CodeGen/BPF/preserve-static-offset/store-pai.ll` and `llvm/test/CodeGen/BPF/preserve-static-offset/load-undo-chain-oob.ll`. You might reuse same intrinsics, if you need to guarantee that gep is never separated from load/store.

**Comment by jordalgo** [comment]
@eddyz87 Do you know of a way to add an attribute (namely "preserve_static_offset") to our struct types created in LLVM IR? Would that solve this issue?

**Comment by eddyz87** [comment]
> @eddyz87 Do you know of a way to add an attribute (namely "preserve_static_offset") to our struct types created in LLVM IR? Would that solve this issue?

@jordalgo , this attribute is clang-specific, it is not represented in IR.
Here is the commits adding the feature: 
030b8cb1561d - [BPF] Attribute preserve_static_offset for structs (12 months ago)
- At clang level it looks for access to fields of structures declared with this attribute, such accesses are wrapped with a call to `@llvm.preserve.static.offset`;
- At llvm level, a transformation (`BPFPreserveStaticOffsetPass`) is installed early in the optimization pipeline, which looks for llvm.preserve.static.offset+GEP+load/store chains and replaces these chains with calls to `llvm.bpf.getelementptr.and.{load,store}`.

To get use of these you either have to generate llvm.preserve.static.offset+GEP+load/store chains, or do direct calls to `llvm.bpf.getelementptr.and.load`.

@viktormalik says that bpftrace generates the following code:

```
  %14 = ptrtoint ptr %0 to i64
  %15 = add i64 %14, 16
  %16 = inttoptr i64 %15 to ptr
  %17 = load volatile i64, ptr %16, align 8
```

You can either change the part of the `bpftrace` responsible for this generation to use `llvm.bpf.getelementptr.and.load`, or write an additional pass that collapses chains as above to a `llvm.bpf.getelementptr.and.load` call. I don't see any semantic obstacles for such transformation.

Wdyt?

**Comment by amscanne** [comment]
Is there a separate existing issue for the types? I'd be happy to file one if not, and then I think this one should be closed.

**Comment by jordalgo** [comment]
> Is there a separate existing issue for the types?

I couldn't easily find one, so please feel free to file a new issue.
