### ISSUE TITLE
Error message for non existent probe needs improving

### ISSUE THREAD

**Issue by tyroguru** [bpftrace/bpftrace#587]
I'd missed a character off a probe name and the error message returned for this non-existent probe is not that helpful:

```
# bpftrace -e 't:syscalls:sys_enter_execv{@[probe] = count();}'
Attaching 1 probe...
open(/sys/kernel/debug/tracing/events/syscalls/sys_enter_execv/id): No such file or directory
Error attaching probe: tracepoint:syscalls:sys_enter_execv
```

An error message along the lines of:

```
Error attaching probe: tracepoint:syscalls:sys_enter_execv: Non existent probe
```

or 

```
Error attaching probe: tracepoint:syscalls:sys_enter_execv: Probe not found
```

may be more useful.

Also, please remove the message about the failed `open()`.

**Comment by amscanne** [comment]
@jordalgo I'm a bit confused about this, since AFAICT, this has had a structured error since c27566ff0, which is before the issue was filed. The current failure is simply:

```
stdin:1:1-27: ERROR: tracepoint not found: syscalls:sys_enter_execv
```

I suspect that this is worth closing as obsolete.
