### ISSUE TITLE
func only matches kretprobe_trampoline on kretprobes

### ISSUE THREAD

**Issue by brendangregg** [bpftrace/bpftrace#68]
```
# bpftrace -e 'kretprobe:vfs_* { @[func] = count(); }'
Attaching 53 probes...
cannot attach kprobe, Invalid argument
Warning: could not attach probe kretprobe:vfs_dedupe_get_page.isra.21, skipping.
^C

@[kretprobe_trampoline]: 438
```

Would be nice if `func` could match the function on kretprobe, intsead of only ever returning `kretprobe_trampoline`. If that's not possible, it should be documented in the reference guide.

**Comment by cyphar** [comment]
#101 is a separate issue -- currently `func` is implemented by fetching the `pc` and unlike with `kretprobe` stacks I think it would be quite *ugly* to fake `pc` as well in-kernel (maybe it's not even practical to do this). So maybe `bpftrace` should instead get the stack but only the first entry? I'm not sure how much of an impact on the BPF code size this would be though...

**Comment by cyphar** [comment]
I think `bpf_get_stack` (as opposed to `_get_stackid`) would let us just fetch the top-most entry of the stack...
