### ISSUE TITLE
print() should allow for provision of a format specifier string

### ISSUE THREAD

**Issue by tyroguru** [bpftrace/bpftrace#929]
Currently when printing maps we have no control over how the data is formatted. For example, the following script indexes a map with a <String,unsigned long> tuple:

```
# cat cow.bt
#include <linux/mm.h>

kprobe:do_wp_page
{
  $vmf = (struct vm_fault*)arg0;
  @[comm, $vmf->address]  = count();
}
```

However, as we have no control over the format when dumped, the entries of the map are dumped as:

```
@[sh, 94825031122944]: 16
@[sh, 139646127181824]: 17
@[sh, 94825031069696]: 17
```

when really what I want is:

```
@[sh, 0x563E2C4BC000]: 16
@[sh, 0x7F01E5CE1000]: 17
@[sh, 0x563E2C4AF000]: 17
```

**Comment by brendangregg** [comment]
See #56 and #356.

In summary, I think the most intuitive option is for print() to do a simple print with defaults, and printf() does a print with formatting (as it's print-f).

So we need to extend print() to accept anything, and extend printf() to handle maps.

**Comment by tyroguru** [comment]
Thanks @brendangregg - apologies for not noticing the other issues you'd raised on this.

I'm not tied to any particular way really, as long as we get the end result. It would be interesting to see how this fits into a very busy interface like printf().

**Comment by danobi** [comment]
I'm interested in adding structured output support for distributed tracing. 

For example, I want to let the user say "emit these 3 variables and treat them as one unit when you schlep it around logging backends". In a sql-like front end, this would give us 1 row with 3 columns populated (versus 3 columns with 1 column populated).

One way we could take this is @brendangregg 's universal print():
```
print($var1, @var2, arg0);
```

I also think adding a map format specific to printf would be intuitive. We just have to make sure we don't clobber any existing specifiers.

**Comment by danobi** [comment]
> versus 3 columns with 1 populated column

To be clear, the user could just `printf("%s %s %s", $x, $y, $z)`, but it would be hard to reliably pull apart each field (eg what if $x contained the delimiter).

**Comment by ajor** [comment]
Closing as this issue looks very similar to #2952. Please reopen if you feel there's still something missing.
